# ruff: noqa: E501, Q000, RUF001
"""Canonical olympiad subtopic taxonomy used by statement metadata cleanup.

Generated from the approved canonical grouping pasted into the Codex task. Keep
entries deterministic: cleanup uses exact normalized aliases only, not fuzzy matching.
"""

from __future__ import annotations

CANONICAL_SUBTOPIC_TAXONOMY: tuple[tuple[str, str, str], ...] = (('ALG', 'Inequalities and optimization', 'AM-GM'),
 ('ALG', 'Inequalities and optimization', 'weighted AM-GM'),
 ('ALG', 'Inequalities and optimization', 'AM-HM'),
 ('ALG', 'Inequalities and optimization', 'AM-QM'),
 ('ALG', 'Inequalities and optimization', 'RMS-AM'),
 ('ALG', 'Inequalities and optimization', 'Cauchy-Schwarz'),
 ('ALG', 'Inequalities and optimization', 'Titu’s lemma / Engel form'),
 ('ALG', 'Inequalities and optimization', 'Hölder'),
 ('ALG', 'Inequalities and optimization', 'Minkowski'),
 ('ALG', 'Inequalities and optimization', 'power mean'),
 ('ALG', 'Inequalities and optimization', 'Jensen'),
 ('ALG', 'Inequalities and optimization', 'Karamata'),
 ('ALG', 'Inequalities and optimization', 'majorization'),
 ('ALG', 'Inequalities and optimization', 'rearrangement inequality'),
 ('ALG', 'Inequalities and optimization', 'Chebyshev inequality'),
 ('ALG', 'Inequalities and optimization', 'Schur'),
 ('ALG', 'Inequalities and optimization', 'Muirhead'),
 ('ALG', 'Inequalities and optimization', 'Maclaurin inequalities'),
 ('ALG', 'Inequalities and optimization', 'Newton inequalities'),
 ('ALG', 'Inequalities and optimization', 'UVW / pqr method'),
 ('ALG', 'Inequalities and optimization', 'sum of squares / SOS'),
 ('ALG', 'Inequalities and optimization', 'tangent line method'),
 ('ALG', 'Inequalities and optimization', 'smoothing / equalization'),
 ('ALG', 'Inequalities and optimization', 'convexity and concavity'),
 ('ALG', 'Inequalities and optimization', 'log-convexity / log-concavity'),
 ('ALG', 'Inequalities and optimization', 'variance method'),
 ('ALG', 'Inequalities and optimization', 'best constant problems'),
 ('ALG', 'Inequalities and optimization', 'equality case analysis'),
 ('ALG', 'Inequalities and optimization', 'boundary/extremal cases'),
 ('ALG', 'Inequalities and optimization', 'constrained optimization'),
 ('ALG', 'Inequalities and optimization', 'one-variable reduction'),
 ('ALG', 'Inequalities and optimization', 'Lagrange multiplier style arguments'),
 ('ALG', 'Inequalities and optimization', 'radical inequalities'),
 ('ALG', 'Inequalities and optimization', 'rational inequalities'),
 ('ALG', 'Inequalities and optimization', 'reciprocal inequalities'),
 ('ALG', 'Inequalities and optimization', 'trigonometric inequalities'),
 ('ALG', 'Inequalities and optimization', 'triangle-substitution inequalities'),
 ('ALG', 'Inequalities and optimization', 'Ravi substitution'),
 ('ALG', 'Inequalities and optimization', 'homogeneous inequalities'),
 ('ALG', 'Inequalities and optimization', 'symmetric and cyclic inequalities'),
 ('ALG', 'Inequalities and optimization', 'polynomial positivity'),
 ('ALG', 'Inequalities and optimization', 'completing squares'),
 ('ALG', 'Inequalities and optimization', 'sign analysis'),
 ('ALG', 'Inequalities and optimization', 'monotonicity arguments'),
 ('ALG', 'Inequalities and optimization', 'calculus-free optimization'),
 ('ALG', 'Inequalities and optimization', 'tangent-line bounding'),
 ('ALG', 'Inequalities and optimization', 'Jensen-style smoothing'),
 ('ALG', 'Inequalities and optimization', 'weighted Jensen'),
 ('ALG', 'Inequalities and optimization', 'Cauchy/Engel telescoping bounds'),
 ('ALG', 'Inequalities and optimization', 'AM-GM with product constraint'),
 ('ALG', 'Inequalities and optimization', 'AM-GM with normalization'),
 ('ALG', 'Inequalities and optimization', 'inequality forcing equality'),
 ('ALG', 'Inequalities and optimization', 'inequality under triangle constraints'),
 ('ALG', 'Functional equations', 'functional equations'),
 ('ALG', 'Functional equations', 'Cauchy-type functional equations'),
 ('ALG', 'Functional equations', 'Jensen-type functional equations'),
 ('ALG', 'Functional equations', 'd’Alembert-type equations'),
 ('ALG', 'Functional equations', 'additive functional equations'),
 ('ALG', 'Functional equations', 'multiplicative functional equations'),
 ('ALG', 'Functional equations', 'polynomial functional equations'),
 ('ALG', 'Functional equations', 'rational-domain functional equations'),
 ('ALG', 'Functional equations', 'integer-domain functional equations'),
 ('ALG', 'Functional equations', 'finite-domain functional equations'),
 ('ALG', 'Functional equations', 'functional inequalities'),
 ('ALG', 'Functional equations', 'injectivity/surjectivity tricks'),
 ('ALG', 'Functional equations', 'monotonicity in functional equations'),
 ('ALG', 'Functional equations', 'continuity in functional equations'),
 ('ALG', 'Functional equations', 'iteration in functional equations'),
 ('ALG', 'Functional equations', 'fixed-point functional equations'),
 ('ALG', 'Functional equations', 'idempotence, f(f(x)) = f(x)'),
 ('ALG', 'Functional equations', 'self-composition'),
 ('ALG', 'Functional equations', 'translation-type equations'),
 ('ALG', 'Functional equations', 'floor-function functional equations'),
 ('ALG', 'Functional equations', 'image/range analysis'),
 ('ALG', 'Functional equations', 'zero-set analysis'),
 ('ALG', 'Functional equations', 'linearity forcing'),
 ('ALG', 'Functional equations', 'quadratic-type functional equations'),
 ('ALG', 'Functional equations', 'arbitrary-function testing'),
 ('ALG', 'Functional equations', 'symmetry substitutions'),
 ('ALG', 'Functional equations', 'Cauchy stability / almost-additivity'),
 ('ALG', 'Functional equations', 'functional graph viewpoint'),
 ('ALG', 'Polynomials and algebraic manipulation', 'polynomials'),
 ('ALG', 'Polynomials and algebraic manipulation', 'polynomial identities'),
 ('ALG', 'Polynomials and algebraic manipulation', 'coefficient comparison'),
 ('ALG', 'Polynomials and algebraic manipulation', 'coefficient extraction'),
 ('ALG', 'Polynomials and algebraic manipulation', 'factor theorem'),
 ('ALG', 'Polynomials and algebraic manipulation', 'polynomial divisibility'),
 ('ALG', 'Polynomials and algebraic manipulation', 'polynomial congruences'),
 ('ALG', 'Polynomials and algebraic manipulation', 'polynomial interpolation'),
 ('ALG', 'Polynomials and algebraic manipulation', 'Lagrange interpolation'),
 ('ALG', 'Polynomials and algebraic manipulation', 'Newton interpolation'),
 ('ALG', 'Polynomials and algebraic manipulation', 'finite differences'),
 ('ALG', 'Polynomials and algebraic manipulation', 'divided differences'),
 ('ALG', 'Polynomials and algebraic manipulation', 'integer-valued polynomials'),
 ('ALG', 'Polynomials and algebraic manipulation', 'falling factorial basis'),
 ('ALG', 'Polynomials and algebraic manipulation', 'polynomial roots'),
 ('ALG', 'Polynomials and algebraic manipulation', 'real-rootedness'),
 ('ALG', 'Polynomials and algebraic manipulation', 'root bounds'),
 ('ALG', 'Polynomials and algebraic manipulation', 'root interlacing'),
 ('ALG', 'Polynomials and algebraic manipulation', 'discriminant method'),
 ('ALG', 'Polynomials and algebraic manipulation', 'resultants'),
 ('ALG', 'Polynomials and algebraic manipulation', 'Vieta relations'),
 ('ALG', 'Polynomials and algebraic manipulation', 'Vieta jumping style algebra'),
 ('ALG', 'Polynomials and algebraic manipulation', 'symmetric polynomials'),
 ('ALG', 'Polynomials and algebraic manipulation', 'elementary symmetric sums'),
 ('ALG', 'Polynomials and algebraic manipulation', 'Newton sums'),
 ('ALG', 'Polynomials and algebraic manipulation', 'power sums'),
 ('ALG', 'Polynomials and algebraic manipulation', 'Vandermonde determinant'),
 ('ALG', 'Polynomials and algebraic manipulation', 'Chebyshev polynomials'),
 ('ALG', 'Polynomials and algebraic manipulation', 'reciprocal polynomials'),
 ('ALG', 'Polynomials and algebraic manipulation', 'self-reciprocal polynomials'),
 ('ALG', 'Polynomials and algebraic manipulation', 'roots of unity filter'),
 ('ALG', 'Polynomials and algebraic manipulation', 'trigonometric polynomials'),
 ('ALG', 'Polynomials and algebraic manipulation', 'Eneström-Kakeya style root bounds'),
 ('ALG', 'Polynomials and algebraic manipulation', 'irreducibility'),
 ('ALG', 'Polynomials and algebraic manipulation', 'Eisenstein criterion'),
 ('ALG', 'Polynomials and algebraic manipulation', 'Gauss lemma'),
 ('ALG', 'Polynomials and algebraic manipulation', 'polynomial ansatz'),
 ('ALG', 'Polynomials and algebraic manipulation', 'polynomial rigidity'),
 ('ALG', 'Polynomials and algebraic manipulation', 'polynomial maps'),
 ('ALG', 'Polynomials and algebraic manipulation', 'polynomial value sets'),
 ('ALG', 'Polynomials and algebraic manipulation', 'polynomial growth'),
 ('ALG', 'Polynomials and algebraic manipulation', 'polynomial iteration'),
 ('ALG', 'Polynomials and algebraic manipulation', 'formal power series'),
 ('ALG', 'Polynomials and algebraic manipulation', 'generating polynomials'),
 ('ALG', 'Polynomials and algebraic manipulation', 'Laurent polynomials'),
 ('ALG', 'Polynomials and algebraic manipulation', 'sparse polynomials'),
 ('ALG',
  'Polynomials and algebraic manipulation',
  'cyclotomic polynomials, when used algebraically rather than number-theoretically'),
 ('ALG', 'Sequences, recurrences, and series', 'sequences'),
 ('ALG', 'Sequences, recurrences, and series', 'recurrence relations'),
 ('ALG', 'Sequences, recurrences, and series', 'linear recurrences'),
 ('ALG', 'Sequences, recurrences, and series', 'nonlinear recurrences'),
 ('ALG', 'Sequences, recurrences, and series', 'characteristic roots'),
 ('ALG', 'Sequences, recurrences, and series', 'closed forms'),
 ('ALG', 'Sequences, recurrences, and series', 'Fibonacci-type recurrences'),
 ('ALG', 'Sequences, recurrences, and series', 'Lucas-type recurrences'),
 ('ALG', 'Sequences, recurrences, and series', 'Chebyshev recurrences'),
 ('ALG', 'Sequences, recurrences, and series', 'generating functions'),
 ('ALG', 'Sequences, recurrences, and series', 'exponential generating functions'),
 ('ALG', 'Sequences, recurrences, and series', 'telescoping sums'),
 ('ALG', 'Sequences, recurrences, and series', 'telescoping products'),
 ('ALG', 'Sequences, recurrences, and series', 'summation by parts / Abel summation'),
 ('ALG', 'Sequences, recurrences, and series', 'finite-difference sequences'),
 ('ALG', 'Sequences, recurrences, and series', 'monotone sequences'),
 ('ALG', 'Sequences, recurrences, and series', 'bounded sequences'),
 ('ALG', 'Sequences, recurrences, and series', 'convergence'),
 ('ALG', 'Sequences, recurrences, and series', 'limits'),
 ('ALG', 'Sequences, recurrences, and series', 'asymptotic estimates'),
 ('ALG', 'Sequences, recurrences, and series', 'Stolz-Cesàro'),
 ('ALG', 'Sequences, recurrences, and series', 'series bounds'),
 ('ALG', 'Sequences, recurrences, and series', 'harmonic sums'),
 ('ALG', 'Sequences, recurrences, and series', 'recurrence modulo m, when algebraic rather than number-theoretic'),
 ('ALG', 'Sequences, recurrences, and series', 'periodic sequences'),
 ('ALG', 'Sequences, recurrences, and series', 'eventual periodicity'),
 ('ALG', 'Sequences, recurrences, and series', 'floor sequences'),
 ('ALG', 'Sequences, recurrences, and series', 'Beatty-type sequences, when treated analytically'),
 ('ALG', 'Sequences, recurrences, and series', 'recursive construction'),
 ('ALG', 'Sequences, recurrences, and series', 'iterative processes'),
 ('ALG', 'Sequences, recurrences, and series', 'dynamical sequences'),
 ('ALG', 'Sequences, recurrences, and series', 'fixed-point iteration'),
 ('ALG', 'Sequences, recurrences, and series', 'stability of recurrences'),
 ('ALG', 'Sequences, recurrences, and series', 'leading-term/asymptotic comparison'),
 ('ALG', 'Algebraic structures and linear algebra', 'linear algebra'),
 ('ALG', 'Algebraic structures and linear algebra', 'matrices'),
 ('ALG', 'Algebraic structures and linear algebra', 'determinants'),
 ('ALG', 'Algebraic structures and linear algebra', 'rank'),
 ('ALG', 'Algebraic structures and linear algebra', 'eigenvalues'),
 ('ALG', 'Algebraic structures and linear algebra', 'eigenvectors'),
 ('ALG', 'Algebraic structures and linear algebra', 'characteristic polynomials'),
 ('ALG', 'Algebraic structures and linear algebra', 'Cayley-Hamilton'),
 ('ALG', 'Algebraic structures and linear algebra', 'Gram matrices'),
 ('ALG', 'Algebraic structures and linear algebra', 'positive semidefinite forms'),
 ('ALG', 'Algebraic structures and linear algebra', 'quadratic forms'),
 ('ALG', 'Algebraic structures and linear algebra', 'bilinear forms'),
 ('ALG', 'Algebraic structures and linear algebra', 'inner products'),
 ('ALG', 'Algebraic structures and linear algebra', 'vector spaces'),
 ('ALG', 'Algebraic structures and linear algebra', 'modules'),
 ('ALG', 'Algebraic structures and linear algebra', 'rings'),
 ('ALG', 'Algebraic structures and linear algebra', 'ideals'),
 ('ALG', 'Algebraic structures and linear algebra', 'quotient rings'),
 ('ALG', 'Algebraic structures and linear algebra', 'fields'),
 ('ALG', 'Algebraic structures and linear algebra', 'finite fields, when used algebraically'),
 ('ALG', 'Algebraic structures and linear algebra', 'group actions'),
 ('ALG', 'Algebraic structures and linear algebra', 'group invariants'),
 ('ALG', 'Algebraic structures and linear algebra', 'homomorphisms'),
 ('ALG', 'Algebraic structures and linear algebra', 'automorphisms'),
 ('ALG', 'Algebraic structures and linear algebra', 'semigroups'),
 ('ALG', 'Algebraic structures and linear algebra', 'monoids'),
 ('ALG', 'Algebraic structures and linear algebra', 'Boolean algebra'),
 ('ALG', 'Algebraic structures and linear algebra', 'idempotents'),
 ('ALG', 'Algebraic structures and linear algebra', 'nilpotents'),
 ('ALG', 'Algebraic structures and linear algebra', 'Möbius transformations'),
 ('ALG', 'Algebraic structures and linear algebra', 'linear fractional transformations'),
 ('ALG', 'Algebraic structures and linear algebra', 'affine maps'),
 ('ALG', 'Algebraic structures and linear algebra', 'affine transformations'),
 ('ALG', 'Algebraic structures and linear algebra', 'rational functions'),
 ('ALG', 'Algebraic structures and linear algebra', 'algebraic numbers'),
 ('ALG', 'Algebraic structures and linear algebra', 'conjugates'),
 ('ALG', 'Algebraic structures and linear algebra', 'minimal polynomials'),
 ('ALG', 'Algebraic structures and linear algebra', 'algebraic integers, when used structurally'),
 ('ALG', 'Algebraic structures and linear algebra', 'norms, when not primarily number-theoretic'),
 ('ALG', 'Equations, substitutions, and transformations', 'equation solving'),
 ('ALG', 'Equations, substitutions, and transformations', 'systems of equations'),
 ('ALG', 'Equations, substitutions, and transformations', 'symmetric systems'),
 ('ALG', 'Equations, substitutions, and transformations', 'cyclic systems'),
 ('ALG', 'Equations, substitutions, and transformations', 'radical equations'),
 ('ALG', 'Equations, substitutions, and transformations', 'rational equations'),
 ('ALG', 'Equations, substitutions, and transformations', 'quadratic equations'),
 ('ALG', 'Equations, substitutions, and transformations', 'cubic equations'),
 ('ALG', 'Equations, substitutions, and transformations', 'quartic/resolvent-style manipulation'),
 ('ALG', 'Equations, substitutions, and transformations', 'discriminant-square constraints'),
 ('ALG', 'Equations, substitutions, and transformations', 'homogeneity'),
 ('ALG', 'Equations, substitutions, and transformations', 'homogenization'),
 ('ALG', 'Equations, substitutions, and transformations', 'normalization'),
 ('ALG', 'Equations, substitutions, and transformations', 'substitution'),
 ('ALG', 'Equations, substitutions, and transformations', 'reciprocal substitution'),
 ('ALG', 'Equations, substitutions, and transformations', 'logarithmic substitution'),
 ('ALG', 'Equations, substitutions, and transformations', 'tangent-half-angle substitution'),
 ('ALG', 'Equations, substitutions, and transformations', 'pqr / uvw substitution'),
 ('ALG', 'Equations, substitutions, and transformations', 'parameterization'),
 ('ALG', 'Equations, substitutions, and transformations', 'rational parameterization'),
 ('ALG', 'Equations, substitutions, and transformations', 'completing the square'),
 ('ALG', 'Equations, substitutions, and transformations', 'factorization tricks'),
 ('ALG', 'Equations, substitutions, and transformations', 'difference of squares/cubes'),
 ('ALG', 'Equations, substitutions, and transformations', 'sum of cubes identity'),
 ('ALG', 'Equations, substitutions, and transformations', 'Sophie Germain identity'),
 ('ALG', 'Equations, substitutions, and transformations', 'clever identity spotting'),
 ('ALG', 'Equations, substitutions, and transformations', 'sign splitting'),
 ('ALG', 'Equations, substitutions, and transformations', 'domain splitting'),
 ('ALG', 'Equations, substitutions, and transformations', 'boundary checking'),
 ('ALG', 'Equations, substitutions, and transformations', 'equality forcing'),
 ('ALG', 'Equations, substitutions, and transformations', 'ansatz methods'),
 ('ALG', 'Equations, substitutions, and transformations', 'algebraic reduction'),
 ('ALG', 'Equations, substitutions, and transformations', 'algebraic rigidity'),
 ('NT', 'Divisibility, gcd, lcm, and primes', 'divisibility'),
 ('NT', 'Divisibility, gcd, lcm, and primes', 'divisibility conditions'),
 ('NT', 'Divisibility, gcd, lcm, and primes', 'divisibility chains'),
 ('NT', 'Divisibility, gcd, lcm, and primes', 'divisibility graphs'),
 ('NT', 'Divisibility, gcd, lcm, and primes', 'gcd'),
 ('NT', 'Divisibility, gcd, lcm, and primes', 'lcm'),
 ('NT', 'Divisibility, gcd, lcm, and primes', 'gcd-lcm identities'),
 ('NT', 'Divisibility, gcd, lcm, and primes', 'Euclidean algorithm'),
 ('NT', 'Divisibility, gcd, lcm, and primes', 'Bézout identity'),
 ('NT', 'Divisibility, gcd, lcm, and primes', 'coprimality'),
 ('NT', 'Divisibility, gcd, lcm, and primes', 'pairwise coprimality'),
 ('NT', 'Divisibility, gcd, lcm, and primes', 'prime factorization'),
 ('NT', 'Divisibility, gcd, lcm, and primes', 'primes'),
 ('NT', 'Divisibility, gcd, lcm, and primes', 'composite numbers'),
 ('NT', 'Divisibility, gcd, lcm, and primes', 'prime divisors'),
 ('NT', 'Divisibility, gcd, lcm, and primes', 'smallest prime factor'),
 ('NT', 'Divisibility, gcd, lcm, and primes', 'largest prime factor'),
 ('NT', 'Divisibility, gcd, lcm, and primes', 'prime support'),
 ('NT', 'Divisibility, gcd, lcm, and primes', 'prime exponent vectors'),
 ('NT', 'Divisibility, gcd, lcm, and primes', 'prime powers'),
 ('NT', 'Divisibility, gcd, lcm, and primes', 'squarefree numbers'),
 ('NT', 'Divisibility, gcd, lcm, and primes', 'squarefree kernel'),
 ('NT', 'Divisibility, gcd, lcm, and primes', 'squareful/powerful numbers'),
 ('NT', 'Divisibility, gcd, lcm, and primes', 'perfect powers'),
 ('NT', 'Divisibility, gcd, lcm, and primes', 'perfect squares'),
 ('NT', 'Divisibility, gcd, lcm, and primes', 'perfect cubes'),
 ('NT', 'Divisibility, gcd, lcm, and primes', 'divisors'),
 ('NT', 'Divisibility, gcd, lcm, and primes', 'divisor function tau(n)'),
 ('NT', 'Divisibility, gcd, lcm, and primes', 'sum-of-divisors function sigma(n)'),
 ('NT', 'Divisibility, gcd, lcm, and primes', 'Euler phi function'),
 ('NT', 'Divisibility, gcd, lcm, and primes', 'radical rad(n)'),
 ('NT', 'Divisibility, gcd, lcm, and primes', 'abundant numbers'),
 ('NT', 'Divisibility, gcd, lcm, and primes', 'highly composite numbers'),
 ('NT', 'Divisibility, gcd, lcm, and primes', 'practical numbers'),
 ('NT', 'Divisibility, gcd, lcm, and primes', 'divisor lattices'),
 ('NT', 'Divisibility, gcd, lcm, and primes', 'divisor chains'),
 ('NT', 'Divisibility, gcd, lcm, and primes', 'divisor bounds'),
 ('NT', 'Divisibility, gcd, lcm, and primes', 'smooth numbers'),
 ('NT', 'Divisibility, gcd, lcm, and primes', 'primorials'),
 ('NT', 'Divisibility, gcd, lcm, and primes', 'Euclid trick'),
 ('NT', 'Divisibility, gcd, lcm, and primes', 'infinitude of primes'),
 ('NT', 'Divisibility, gcd, lcm, and primes', 'Bertrand-type prime bounds'),
 ('NT', 'Divisibility, gcd, lcm, and primes', 'primes in intervals'),
 ('NT', 'Divisibility, gcd, lcm, and primes', 'primes in arithmetic progressions, if only used lightly'),
 ('NT', 'Congruences and modular arithmetic', 'modular arithmetic'),
 ('NT', 'Congruences and modular arithmetic', 'congruences'),
 ('NT', 'Congruences and modular arithmetic', 'residue classes'),
 ('NT', 'Congruences and modular arithmetic', 'complete residue systems'),
 ('NT', 'Congruences and modular arithmetic', 'reduced residue systems'),
 ('NT', 'Congruences and modular arithmetic', 'modular inverses'),
 ('NT', 'Congruences and modular arithmetic', 'modular equations'),
 ('NT', 'Congruences and modular arithmetic', 'modular roots'),
 ('NT', 'Congruences and modular arithmetic', 'modular lifting'),
 ('NT', 'Congruences and modular arithmetic', 'modular obstructions'),
 ('NT', 'Congruences and modular arithmetic', 'modular construction'),
 ('NT', 'Congruences and modular arithmetic', 'Chinese remainder theorem / CRT'),
 ('NT', 'Congruences and modular arithmetic', 'Fermat’s little theorem'),
 ('NT', 'Congruences and modular arithmetic', 'Euler’s theorem'),
 ('NT', 'Congruences and modular arithmetic', 'Wilson’s theorem'),
 ('NT', 'Congruences and modular arithmetic', 'Wilson-type products'),
 ('NT', 'Congruences and modular arithmetic', 'modular orders'),
 ('NT', 'Congruences and modular arithmetic', 'multiplicative order'),
 ('NT', 'Congruences and modular arithmetic', 'primitive roots'),
 ('NT', 'Congruences and modular arithmetic', 'unit groups modulo n'),
 ('NT', 'Congruences and modular arithmetic', 'cyclic groups modulo p'),
 ('NT', 'Congruences and modular arithmetic', 'Carmichael function'),
 ('NT', 'Congruences and modular arithmetic', 'quadratic residues'),
 ('NT', 'Congruences and modular arithmetic', 'cubic residues'),
 ('NT', 'Congruences and modular arithmetic', 'higher power residues'),
 ('NT', 'Congruences and modular arithmetic', 'Legendre symbol'),
 ('NT', 'Congruences and modular arithmetic', 'Jacobi symbol'),
 ('NT', 'Congruences and modular arithmetic', 'Euler criterion'),
 ('NT', 'Congruences and modular arithmetic', 'quadratic reciprocity'),
 ('NT', 'Congruences and modular arithmetic', 'roots modulo prime powers'),
 ('NT', 'Congruences and modular arithmetic', 'Hensel lifting'),
 ('NT', 'Congruences and modular arithmetic', 'modular polynomials'),
 ('NT', 'Congruences and modular arithmetic', 'modular periodicity'),
 ('NT', 'Congruences and modular arithmetic', 'modular dynamics'),
 ('NT', 'Congruences and modular arithmetic', 'modular invariants'),
 ('NT', 'Congruences and modular arithmetic', 'congruence sieves'),
 ('NT', 'Congruences and modular arithmetic', 'residue design'),
 ('NT', 'Congruences and modular arithmetic', 'residue covering'),
 ('NT', 'Congruences and modular arithmetic', 'modular digit constraints'),
 ('NT', 'p-adic and valuation methods', 'p-adic valuation'),
 ('NT', 'p-adic and valuation methods', 'v_p'),
 ('NT', 'p-adic and valuation methods', '2-adic valuation'),
 ('NT', 'p-adic and valuation methods', '3-adic valuation'),
 ('NT', 'p-adic and valuation methods', '5-adic valuation'),
 ('NT', 'p-adic and valuation methods', 'p-adic congruences'),
 ('NT', 'p-adic and valuation methods', 'p-adic lifting'),
 ('NT', 'p-adic and valuation methods', 'p-adic continuity'),
 ('NT', 'p-adic and valuation methods', 'p-adic roots'),
 ('NT', 'p-adic and valuation methods', 'p-adic polynomial functions'),
 ('NT', 'p-adic and valuation methods', 'Mahler basis'),
 ('NT', 'p-adic and valuation methods', 'Hensel-style lifting'),
 ('NT', 'p-adic and valuation methods', 'LTE'),
 ('NT', 'p-adic and valuation methods', 'lifting the exponent'),
 ('NT', 'p-adic and valuation methods', 'Legendre formula'),
 ('NT', 'p-adic and valuation methods', 'Kummer theorem'),
 ('NT', 'p-adic and valuation methods', 'Lucas theorem'),
 ('NT', 'p-adic and valuation methods', 'factorial valuations'),
 ('NT', 'p-adic and valuation methods', 'binomial valuations'),
 ('NT', 'p-adic and valuation methods', 'carry analysis'),
 ('NT', 'p-adic and valuation methods', 'base-p digit analysis'),
 ('NT', 'p-adic and valuation methods', 'valuation chasing'),
 ('NT', 'p-adic and valuation methods', 'valuation growth'),
 ('NT', 'p-adic and valuation methods', 'valuation descent'),
 ('NT', 'p-adic and valuation methods', 'valuation parity'),
 ('NT', 'p-adic and valuation methods', 'valuation bounds'),
 ('NT', 'p-adic and valuation methods', 'p-adic obstruction'),
 ('NT', 'p-adic and valuation methods', 'p-adic construction'),
 ('NT', 'p-adic and valuation methods', 'Wieferich-type obstruction'),
 ('NT', 'p-adic and valuation methods', 'Wolstenholme-type congruence'),
 ('NT', 'p-adic and valuation methods', 'p-adic density / local-global flavor'),
 ('NT', 'Diophantine equations and descent', 'Diophantine equations'),
 ('NT', 'Diophantine equations and descent', 'Diophantine inequalities'),
 ('NT', 'Diophantine equations and descent', 'integer solutions'),
 ('NT', 'Diophantine equations and descent', 'rational solutions'),
 ('NT', 'Diophantine equations and descent', 'descent'),
 ('NT', 'Diophantine equations and descent', 'infinite descent'),
 ('NT', 'Diophantine equations and descent', 'Vieta jumping'),
 ('NT', 'Diophantine equations and descent', 'Vieta-style descent'),
 ('NT', 'Diophantine equations and descent', 'Pell equations'),
 ('NT', 'Diophantine equations and descent', 'Pell-type recurrences'),
 ('NT', 'Diophantine equations and descent', 'Markov-type equations'),
 ('NT', 'Diophantine equations and descent', 'Pythagorean triples'),
 ('NT', 'Diophantine equations and descent', 'Heronian triangles'),
 ('NT', 'Diophantine equations and descent', 'discriminant-square method'),
 ('NT', 'Diophantine equations and descent', 'quadratic Diophantine equations'),
 ('NT', 'Diophantine equations and descent', 'cubic Diophantine equations'),
 ('NT', 'Diophantine equations and descent', 'exponential Diophantine equations'),
 ('NT', 'Diophantine equations and descent', 'factorial Diophantine equations'),
 ('NT', 'Diophantine equations and descent', 'Catalan / Mihăilescu flavor'),
 ('NT', 'Diophantine equations and descent', 'Ljunggren / Nagell flavor'),
 ('NT', 'Diophantine equations and descent', 'S-unit equations'),
 ('NT', 'Diophantine equations and descent', 'unit equations'),
 ('NT', 'Diophantine equations and descent', 'Egyptian fractions'),
 ('NT', 'Diophantine equations and descent', 'Frobenius coin problem'),
 ('NT', 'Diophantine equations and descent', 'numerical semigroups'),
 ('NT', 'Diophantine equations and descent', 'rational points on conics'),
 ('NT', 'Diophantine equations and descent', 'conic parameterization'),
 ('NT', 'Diophantine equations and descent', 'elliptic-curve flavor, if only heuristic'),
 ('NT', 'Diophantine equations and descent', 'bounding by growth'),
 ('NT', 'Diophantine equations and descent', 'bounding by divisibility'),
 ('NT', 'Diophantine equations and descent', 'modular elimination'),
 ('NT', 'Diophantine equations and descent', 'local obstruction'),
 ('NT', 'Diophantine equations and descent', 'primitive solution reduction'),
 ('NT', 'Diophantine equations and descent', 'coprime factor splitting'),
 ('NT', 'Diophantine equations and descent', 'difference of squares'),
 ('NT', 'Diophantine equations and descent', 'sum of two squares'),
 ('NT', 'Diophantine equations and descent', 'sum of three squares'),
 ('NT', 'Diophantine equations and descent', 'sum of powers'),
 ('NT', 'Algebraic number theory flavor', 'Gaussian integers'),
 ('NT', 'Algebraic number theory flavor', 'Eisenstein integers'),
 ('NT', 'Algebraic number theory flavor', 'quadratic fields'),
 ('NT', 'Algebraic number theory flavor', 'quadratic integer rings'),
 ('NT', 'Algebraic number theory flavor', 'algebraic norms'),
 ('NT', 'Algebraic number theory flavor', 'norm forms'),
 ('NT', 'Algebraic number theory flavor', 'UFD arguments'),
 ('NT', 'Algebraic number theory flavor', 'factorization in Z[i]'),
 ('NT', 'Algebraic number theory flavor', 'factorization in Z[omega]'),
 ('NT', 'Algebraic number theory flavor', 'sum of two squares theorem'),
 ('NT', 'Algebraic number theory flavor', 'Eisenstein norm'),
 ('NT', 'Algebraic number theory flavor', 'Gaussian integer norm'),
 ('NT', 'Algebraic number theory flavor', 'binary quadratic forms'),
 ('NT', 'Algebraic number theory flavor', 'representation by x^2 + y^2'),
 ('NT', 'Algebraic number theory flavor', 'representation by x^2 + d y^2'),
 ('NT', 'Algebraic number theory flavor', 'cyclotomic factorization'),
 ('NT', 'Algebraic number theory flavor', 'cyclotomic polynomials'),
 ('NT', 'Algebraic number theory flavor', 'primitive divisors'),
 ('NT', 'Algebraic number theory flavor', 'Zsigmondy theorem flavor'),
 ('NT', 'Algebraic number theory flavor', 'primitive prime divisors'),
 ('NT', 'Algebraic number theory flavor', 'Lucas sequences'),
 ('NT', 'Algebraic number theory flavor', 'Fibonacci divisibility'),
 ('NT', 'Algebraic number theory flavor', 'Carmichael primitive divisor arguments'),
 ('NT', 'Algebraic number theory flavor', 'algebraic integer conjugation'),
 ('NT', 'Algebraic number theory flavor', 'minimal polynomial arguments'),
 ('NT', 'Algebraic number theory flavor', 'field degree / irrationality obstruction'),
 ('NT', 'Algebraic number theory flavor', 'Hilbert 90 flavor, if advanced'),
 ('NT', 'Algebraic number theory flavor', 'local-global obstruction'),
 ('NT', 'Base, digit, and automata number theory', 'base representations'),
 ('NT', 'Base, digit, and automata number theory', 'binary representation'),
 ('NT', 'Base, digit, and automata number theory', 'ternary representation'),
 ('NT', 'Base, digit, and automata number theory', 'decimal representation'),
 ('NT', 'Base, digit, and automata number theory', 'base-b expansion'),
 ('NT', 'Base, digit, and automata number theory', 'digit sums'),
 ('NT', 'Base, digit, and automata number theory', 'digital root'),
 ('NT', 'Base, digit, and automata number theory', 'digit products'),
 ('NT', 'Base, digit, and automata number theory', 'digit constraints'),
 ('NT', 'Base, digit, and automata number theory', 'digit DP'),
 ('NT', 'Base, digit, and automata number theory', 'carries'),
 ('NT', 'Base, digit, and automata number theory', 'carry-free construction'),
 ('NT', 'Base, digit, and automata number theory', 'no-carry tricks'),
 ('NT', 'Base, digit, and automata number theory', 'binary carries'),
 ('NT', 'Base, digit, and automata number theory', 'base-10 carries'),
 ('NT', 'Base, digit, and automata number theory', 'base-p carries'),
 ('NT', 'Base, digit, and automata number theory', 'repunits'),
 ('NT', 'Base, digit, and automata number theory', 'repeating decimals'),
 ('NT', 'Base, digit, and automata number theory', 'decimal periods'),
 ('NT', 'Base, digit, and automata number theory', 'palindromes'),
 ('NT', 'Base, digit, and automata number theory', 'automorphic numbers'),
 ('NT', 'Base, digit, and automata number theory', 'leading digits'),
 ('NT', 'Base, digit, and automata number theory', 'Benford-type logarithmic mantissas'),
 ('NT', 'Base, digit, and automata number theory', 'factorial base'),
 ('NT', 'Base, digit, and automata number theory', 'negative base'),
 ('NT', 'Base, digit, and automata number theory', 'mixed-radix representation'),
 ('NT', 'Base, digit, and automata number theory', 'automata on digits'),
 ('NT', 'Base, digit, and automata number theory', 'finite-state residue systems'),
 ('NT', 'Base, digit, and automata number theory', 'Thue-Morse / automatic sequences, when used arithmetically'),
 ('NT', 'Base, digit, and automata number theory', 'popcount'),
 ('NT', 'Base, digit, and automata number theory', 'binary weight'),
 ('NT', 'Base, digit, and automata number theory', 'Lucas digit theorem'),
 ('NT', 'Base, digit, and automata number theory', 'base-p digit stratification'),
 ('NT', 'Additive and multiplicative number theory', 'arithmetic progressions'),
 ('NT', 'Additive and multiplicative number theory', 'geometric progressions'),
 ('NT', 'Additive and multiplicative number theory', 'AP/GP avoidance'),
 ('NT', 'Additive and multiplicative number theory', '3-term AP'),
 ('NT', 'Additive and multiplicative number theory', '3-term GP'),
 ('NT', 'Additive and multiplicative number theory', 'additive bases'),
 ('NT', 'Additive and multiplicative number theory', 'additive combinatorics over integers'),
 ('NT', 'Additive and multiplicative number theory', 'sumsets'),
 ('NT', 'Additive and multiplicative number theory', 'product sets'),
 ('NT', 'Additive and multiplicative number theory', 'sum-product tension'),
 ('NT', 'Additive and multiplicative number theory', 'sum-free sets'),
 ('NT', 'Additive and multiplicative number theory', 'zero-sum sequences'),
 ('NT', 'Additive and multiplicative number theory', 'EGZ theorem flavor'),
 ('NT', 'Additive and multiplicative number theory', 'Cauchy-Davenport'),
 ('NT', 'Additive and multiplicative number theory', 'Davenport constant'),
 ('NT', 'Additive and multiplicative number theory', 'Schur/Rado flavor'),
 ('NT', 'Additive and multiplicative number theory', 'van der Waerden flavor'),
 ('NT', 'Additive and multiplicative number theory', 'Sidon sets'),
 ('NT', 'Additive and multiplicative number theory', 'distinct differences'),
 ('NT', 'Additive and multiplicative number theory', 'difference sets'),
 ('NT', 'Additive and multiplicative number theory', 'modular additive groups'),
 ('NT', 'Additive and multiplicative number theory', 'multiplicative groups'),
 ('NT', 'Additive and multiplicative number theory', 'orders of powers'),
 ('NT', 'Additive and multiplicative number theory', 'density arguments'),
 ('NT', 'Additive and multiplicative number theory', 'Dirichlet approximation'),
 ('NT', 'Additive and multiplicative number theory', 'Farey fractions'),
 ('NT', 'Additive and multiplicative number theory', 'Stern-Brocot tree'),
 ('NT', 'Additive and multiplicative number theory', 'continued fractions'),
 ('NT', 'Additive and multiplicative number theory', 'Beatty sequences, when number-theoretic'),
 ('NT', 'Additive and multiplicative number theory', 'Kronecker approximation'),
 ('NT', 'Additive and multiplicative number theory', 'fractional parts'),
 ('NT', 'Additive and multiplicative number theory', 'equidistribution mod 1'),
 ('NT', 'Arithmetic functions', 'Euler phi'),
 ('NT', 'Arithmetic functions', 'tau function'),
 ('NT', 'Arithmetic functions', 'sigma function'),
 ('NT', 'Arithmetic functions', 'Möbius function'),
 ('NT', 'Arithmetic functions', 'Liouville function'),
 ('NT', 'Arithmetic functions', 'omega function'),
 ('NT', 'Arithmetic functions', 'number of prime factors'),
 ('NT', 'Arithmetic functions', 'Dirichlet convolution'),
 ('NT', 'Arithmetic functions', 'divisor sums'),
 ('NT', 'Arithmetic functions', 'summatory divisor function'),
 ('NT', 'Arithmetic functions', 'multiplicative functions'),
 ('NT', 'Arithmetic functions', 'completely multiplicative functions'),
 ('NT', 'Arithmetic functions', 'additive arithmetic functions'),
 ('NT', 'Arithmetic functions', 'inverse phi / inverse sigma flavor'),
 ('NT', 'Arithmetic functions', 'totient chains'),
 ('NT', 'Arithmetic functions', 'divisor-function dynamics'),
 ('NT', 'Arithmetic functions', 'phi/tau/sigma constraints'),
 ('NT', 'Arithmetic functions', 'highly composite number structure'),
 ('NT', 'Arithmetic functions', 'average order estimates, when elementary'),
 ('GEO', 'Core Euclidean geometry', 'angle chasing'),
 ('GEO', 'Core Euclidean geometry', 'directed angles'),
 ('GEO', 'Core Euclidean geometry', 'angle bisectors'),
 ('GEO', 'Core Euclidean geometry', 'parallel lines'),
 ('GEO', 'Core Euclidean geometry', 'perpendicular lines'),
 ('GEO', 'Core Euclidean geometry', 'perpendicular bisectors'),
 ('GEO', 'Core Euclidean geometry', 'congruent triangles'),
 ('GEO', 'Core Euclidean geometry', 'similar triangles'),
 ('GEO', 'Core Euclidean geometry', 'SSS/SAS/ASA similarity/congruence'),
 ('GEO', 'Core Euclidean geometry', 'law of sines'),
 ('GEO', 'Core Euclidean geometry', 'law of cosines'),
 ('GEO', 'Core Euclidean geometry', 'extended law of sines'),
 ('GEO', 'Core Euclidean geometry', 'trigonometric Ceva'),
 ('GEO', 'Core Euclidean geometry', 'trigonometric Menelaus'),
 ('GEO', 'Core Euclidean geometry', 'Ceva'),
 ('GEO', 'Core Euclidean geometry', 'Menelaus'),
 ('GEO', 'Core Euclidean geometry', 'mass points'),
 ('GEO', 'Core Euclidean geometry', 'ratio chasing'),
 ('GEO', 'Core Euclidean geometry', 'length chasing'),
 ('GEO', 'Core Euclidean geometry', 'area chasing'),
 ('GEO', 'Core Euclidean geometry', 'area ratios'),
 ('GEO', 'Core Euclidean geometry', 'barycentric coordinates'),
 ('GEO', 'Core Euclidean geometry', 'trilinear coordinates'),
 ('GEO', 'Core Euclidean geometry', 'affine coordinates'),
 ('GEO', 'Core Euclidean geometry', 'vector geometry'),
 ('GEO', 'Core Euclidean geometry', 'complex plane methods'),
 ('GEO', 'Core Euclidean geometry', 'coordinate bash'),
 ('GEO', 'Core Euclidean geometry', 'analytic geometry'),
 ('GEO', 'Core Euclidean geometry', 'determinant/shoelace area'),
 ('GEO', 'Core Euclidean geometry', 'projection methods'),
 ('GEO', 'Core Euclidean geometry', 'locus problems'),
 ('GEO', 'Core Euclidean geometry', 'extremal geometry'),
 ('GEO', 'Core Euclidean geometry', 'triangle inequality methods'),
 ('GEO', 'Triangle centers and triangle configurations', 'incenter'),
 ('GEO', 'Triangle centers and triangle configurations', 'incircle'),
 ('GEO', 'Triangle centers and triangle configurations', 'contact triangle'),
 ('GEO', 'Triangle centers and triangle configurations', 'intouch triangle'),
 ('GEO', 'Triangle centers and triangle configurations', 'excenter'),
 ('GEO', 'Triangle centers and triangle configurations', 'excircle'),
 ('GEO', 'Triangle centers and triangle configurations', 'excentral triangle'),
 ('GEO', 'Triangle centers and triangle configurations', 'circumcenter'),
 ('GEO', 'Triangle centers and triangle configurations', 'circumcircle'),
 ('GEO', 'Triangle centers and triangle configurations', 'orthocenter'),
 ('GEO', 'Triangle centers and triangle configurations', 'orthic triangle'),
 ('GEO', 'Triangle centers and triangle configurations', 'altitude feet'),
 ('GEO', 'Triangle centers and triangle configurations', 'pedal triangle'),
 ('GEO', 'Triangle centers and triangle configurations', 'centroid'),
 ('GEO', 'Triangle centers and triangle configurations', 'median geometry'),
 ('GEO', 'Triangle centers and triangle configurations', 'Euler line'),
 ('GEO', 'Triangle centers and triangle configurations', 'nine-point circle'),
 ('GEO', 'Triangle centers and triangle configurations', 'Gergonne point'),
 ('GEO', 'Triangle centers and triangle configurations', 'Nagel point'),
 ('GEO', 'Triangle centers and triangle configurations', 'Spieker center'),
 ('GEO', 'Triangle centers and triangle configurations', 'Fermat/Torricelli point'),
 ('GEO', 'Triangle centers and triangle configurations', 'Brocard point'),
 ('GEO', 'Triangle centers and triangle configurations', 'symmedian'),
 ('GEO', 'Triangle centers and triangle configurations', 'isogonal conjugacy'),
 ('GEO', 'Triangle centers and triangle configurations', 'isotomic conjugacy'),
 ('GEO', 'Triangle centers and triangle configurations', 'mixtilinear circle'),
 ('GEO', 'Triangle centers and triangle configurations', 'A-mixtilinear incircle'),
 ('GEO', 'Triangle centers and triangle configurations', 'arc midpoint'),
 ('GEO', 'Triangle centers and triangle configurations', 'midpoint geometry'),
 ('GEO', 'Triangle centers and triangle configurations', 'midline / midsegment'),
 ('GEO', 'Triangle centers and triangle configurations', 'cevian geometry'),
 ('GEO', 'Triangle centers and triangle configurations', 'cevian triangle'),
 ('GEO', 'Triangle centers and triangle configurations', 'excircle/incircle interactions'),
 ('GEO', 'Triangle centers and triangle configurations', 'incenter-excenter lemmas'),
 ('GEO', 'Triangle centers and triangle configurations', 'orthocenter-circumcenter relations'),
 ('GEO', 'Triangle centers and triangle configurations', 'incenter-circumcenter relations'),
 ('GEO', 'Triangle centers and triangle configurations', 'Euler relation'),
 ('GEO', 'Triangle centers and triangle configurations', 'radius identities'),
 ('GEO', 'Triangle centers and triangle configurations', 'inradius/circumradius formulas'),
 ('GEO', 'Triangle centers and triangle configurations', 'semiperimeter identities'),
 ('GEO', 'Triangle centers and triangle configurations', 'triangle-center inequalities'),
 ('GEO', 'Circle geometry', 'circles'),
 ('GEO', 'Circle geometry', 'cyclic quadrilaterals'),
 ('GEO', 'Circle geometry', 'concyclicity'),
 ('GEO', 'Circle geometry', 'cyclicity criteria'),
 ('GEO', 'Circle geometry', 'tangent-chord theorem'),
 ('GEO', 'Circle geometry', 'tangents'),
 ('GEO', 'Circle geometry', 'secants'),
 ('GEO', 'Circle geometry', 'chords'),
 ('GEO', 'Circle geometry', 'arcs'),
 ('GEO', 'Circle geometry', 'equal arcs'),
 ('GEO', 'Circle geometry', 'equal chords'),
 ('GEO', 'Circle geometry', 'power of a point'),
 ('GEO', 'Circle geometry', 'radical axis'),
 ('GEO', 'Circle geometry', 'radical center'),
 ('GEO', 'Circle geometry', 'coaxal circles'),
 ('GEO', 'Circle geometry', 'common chords'),
 ('GEO', 'Circle geometry', 'circle inversion'),
 ('GEO', 'Circle geometry', 'circle tangency'),
 ('GEO', 'Circle geometry', 'tangent circles'),
 ('GEO', 'Circle geometry', 'Apollonius circle'),
 ('GEO', 'Circle geometry', 'circle of Apollonius'),
 ('GEO', 'Circle geometry', 'circle with diameter'),
 ('GEO', 'Circle geometry', 'Thales circle'),
 ('GEO', 'Circle geometry', 'Miquel point'),
 ('GEO', 'Circle geometry', 'Miquel circles'),
 ('GEO', 'Circle geometry', 'Reim theorem'),
 ('GEO', 'Circle geometry', 'spiral similarity'),
 ('GEO', 'Circle geometry', 'homothety of circles'),
 ('GEO', 'Circle geometry', 'internal/external homothety centers'),
 ('GEO', 'Circle geometry', 'circle pencils'),
 ('GEO', 'Circle geometry', 'orthogonal circles'),
 ('GEO', 'Circle geometry', 'limiting points'),
 ('GEO', 'Circle geometry', 'circle-line intersections'),
 ('GEO', 'Circle geometry', 'cyclic quadrilateral angle conditions'),
 ('GEO', 'Circle geometry', 'Ptolemy'),
 ('GEO', 'Circle geometry', 'Ptolemy inequality'),
 ('GEO', 'Circle geometry', 'bicentric quadrilaterals'),
 ('GEO', 'Circle geometry', 'tangential quadrilaterals'),
 ('GEO', 'Circle geometry', 'Pitot theorem'),
 ('GEO', 'Circle geometry', 'equal tangent lengths'),
 ('GEO', 'Circle geometry', 'tangent power'),
 ('GEO', 'Circle geometry', 'chord length formulas'),
 ('GEO', 'Transformational geometry', 'reflection'),
 ('GEO', 'Transformational geometry', 'reflection across angle bisector'),
 ('GEO', 'Transformational geometry', 'reflection across side'),
 ('GEO', 'Transformational geometry', 'reflection in tangent'),
 ('GEO', 'Transformational geometry', 'rotations'),
 ('GEO', 'Transformational geometry', '60-degree rotation'),
 ('GEO', 'Transformational geometry', '90-degree rotation'),
 ('GEO', 'Transformational geometry', '120-degree rotation'),
 ('GEO', 'Transformational geometry', 'half-turns'),
 ('GEO', 'Transformational geometry', 'homothety'),
 ('GEO', 'Transformational geometry', 'dilation'),
 ('GEO', 'Transformational geometry', 'translation'),
 ('GEO', 'Transformational geometry', 'inversion'),
 ('GEO', 'Transformational geometry', 'inversion at a vertex'),
 ('GEO', 'Transformational geometry', 'inversion in incircle'),
 ('GEO', 'Transformational geometry', 'inversion in circumcircle'),
 ('GEO', 'Transformational geometry', 'isogonal reflection'),
 ('GEO', 'Transformational geometry', 'affine transformation'),
 ('GEO', 'Transformational geometry', 'projective transformation'),
 ('GEO', 'Transformational geometry', 'complex multiplication as rotation/dilation'),
 ('GEO', 'Transformational geometry', 'symmetry'),
 ('GEO', 'Transformational geometry', 'central symmetry'),
 ('GEO', 'Transformational geometry', 'mirror symmetry'),
 ('GEO', 'Transformational geometry', 'unfolding / billiards'),
 ('GEO', 'Transformational geometry', 'stereographic projection'),
 ('GEO', 'Transformational geometry', 'similarity transformations'),
 ('GEO', 'Transformational geometry', 'rigid motions'),
 ('GEO', 'Transformational geometry', 'composition of isometries'),
 ('GEO', 'Projective and advanced geometry', 'projective geometry'),
 ('GEO', 'Projective and advanced geometry', 'cross ratio'),
 ('GEO', 'Projective and advanced geometry', 'harmonic bundles'),
 ('GEO', 'Projective and advanced geometry', 'complete quadrilateral'),
 ('GEO', 'Projective and advanced geometry', 'Pascal theorem'),
 ('GEO', 'Projective and advanced geometry', 'Pappus theorem'),
 ('GEO', 'Projective and advanced geometry', 'Desargues theorem'),
 ('GEO', 'Projective and advanced geometry', 'Brianchon theorem'),
 ('GEO', 'Projective and advanced geometry', 'La Hire theorem'),
 ('GEO', 'Projective and advanced geometry', 'pole-polar'),
 ('GEO', 'Projective and advanced geometry', 'polars'),
 ('GEO', 'Projective and advanced geometry', 'polarity'),
 ('GEO', 'Projective and advanced geometry', 'conics'),
 ('GEO', 'Projective and advanced geometry', 'projective involution'),
 ('GEO', 'Projective and advanced geometry', 'homography'),
 ('GEO', 'Projective and advanced geometry', 'perspectivity'),
 ('GEO', 'Projective and advanced geometry', 'projective Ceva'),
 ('GEO', 'Projective and advanced geometry', 'projective Menelaus'),
 ('GEO', 'Projective and advanced geometry', 'degenerate Pascal'),
 ('GEO', 'Projective and advanced geometry', 'Brokard theorem'),
 ('GEO', 'Projective and advanced geometry', 'Monge theorem'),
 ('GEO', 'Projective and advanced geometry', 'Newton line'),
 ('GEO', 'Projective and advanced geometry', 'Gauss line'),
 ('GEO', 'Projective and advanced geometry', 'radical-axis projective methods'),
 ('GEO', 'Projective and advanced geometry', 'tangent-polar duality'),
 ('GEO', 'Projective and advanced geometry', 'conic polarity'),
 ('GEO', 'Projective and advanced geometry', 'projective transformations'),
 ('GEO', 'Projective and advanced geometry', 'affine-to-projective reduction'),
 ('GEO', 'Projective and advanced geometry', 'complete quadrilateral Miquel geometry'),
 ('GEO', 'Projective and advanced geometry', 'harmonic conjugates'),
 ('GEO', 'Projective and advanced geometry', 'symmedian as pole/polar phenomenon'),
 ('GEO', 'Special configurations and special angles', 'equilateral triangle geometry'),
 ('GEO', 'Special configurations and special angles', '30-60-90 triangle'),
 ('GEO', 'Special configurations and special angles', '45-degree geometry'),
 ('GEO', 'Special configurations and special angles', '120-degree geometry'),
 ('GEO', 'Special configurations and special angles', 'Fermat point / 120-degree configuration'),
 ('GEO', 'Special configurations and special angles', 'isosceles triangle'),
 ('GEO', 'Special configurations and special angles', 'right triangle'),
 ('GEO', 'Special configurations and special angles', 'right-angle chase'),
 ('GEO', 'Special configurations and special angles', 'right-triangle altitude facts'),
 ('GEO', 'Special configurations and special angles', 'rectangle geometry'),
 ('GEO', 'Special configurations and special angles', 'parallelogram geometry'),
 ('GEO', 'Special configurations and special angles', 'rhombus geometry'),
 ('GEO', 'Special configurations and special angles', 'trapezoid geometry'),
 ('GEO', 'Special configurations and special angles', 'isosceles trapezoid'),
 ('GEO', 'Special configurations and special angles', 'quadrilateral geometry'),
 ('GEO', 'Special configurations and special angles', 'cyclic quadrilateral'),
 ('GEO', 'Special configurations and special angles', 'tangential quadrilateral'),
 ('GEO', 'Special configurations and special angles', 'bicentric quadrilateral'),
 ('GEO', 'Special configurations and special angles', 'regular polygon geometry'),
 ('GEO', 'Special configurations and special angles', 'regular pentagon / golden ratio'),
 ('GEO', 'Special configurations and special angles', 'regular hexagon'),
 ('GEO', 'Special configurations and special angles', 'equiangular polygon'),
 ('GEO', 'Special configurations and special angles', 'convex polygon'),
 ('GEO', 'Special configurations and special angles', 'polygon triangulation'),
 ('GEO', 'Special configurations and special angles', 'special-angle chasing'),
 ('GEO', 'Special configurations and special angles', 'adventitious angles'),
 ('GEO', 'Special configurations and special angles', 'Langley-type configurations'),
 ('GEO', 'Special configurations and special angles', 'Morley-type configuration'),
 ('GEO', 'Special configurations and special angles', 'Napoleon/Kiepert flavor'),
 ('GEO', 'Geometric inequalities and optimization', 'triangle inequality'),
 ('GEO', 'Geometric inequalities and optimization', 'side-angle inequality'),
 ('GEO', 'Geometric inequalities and optimization', 'area inequalities'),
 ('GEO', 'Geometric inequalities and optimization', 'perimeter inequalities'),
 ('GEO', 'Geometric inequalities and optimization', 'inradius bounds'),
 ('GEO', 'Geometric inequalities and optimization', 'circumradius bounds'),
 ('GEO', 'Geometric inequalities and optimization', 'Euler inequality'),
 ('GEO', 'Geometric inequalities and optimization', 'Weitzenböck inequality'),
 ('GEO', 'Geometric inequalities and optimization', 'Erdős-Mordell flavor'),
 ('GEO', 'Geometric inequalities and optimization', 'Jensen/trig geometric inequalities'),
 ('GEO', 'Geometric inequalities and optimization', 'projection bounds'),
 ('GEO', 'Geometric inequalities and optimization', 'width/diameter arguments'),
 ('GEO', 'Geometric inequalities and optimization', 'area-perimeter relations'),
 ('GEO', 'Geometric inequalities and optimization', 'extremal triangle'),
 ('GEO', 'Geometric inequalities and optimization', 'extremal quadrilateral'),
 ('GEO', 'Geometric inequalities and optimization', 'extremal point set'),
 ('GEO', 'Geometric inequalities and optimization', 'packing/covering geometry'),
 ('GEO', 'Geometric inequalities and optimization', 'smallest enclosing circle'),
 ('GEO', 'Geometric inequalities and optimization', 'isoperimetric-type arguments'),
 ('GEO', 'Geometric inequalities and optimization', 'convex hull'),
 ('GEO', 'Geometric inequalities and optimization', 'convex polygons'),
 ('GEO', 'Geometric inequalities and optimization', 'support functions'),
 ('GEO', 'Geometric inequalities and optimization', 'rotating calipers'),
 ('GEO', 'Geometric inequalities and optimization', 'geometric probability'),
 ('GEO', 'Geometric inequalities and optimization', 'geometric packing'),
 ('GEO', 'Geometric inequalities and optimization', 'geometric covering'),
 ('GEO', 'Geometric inequalities and optimization', 'empty triangles/polygons'),
 ('GEO', 'Geometric inequalities and optimization', 'incidence geometry'),
 ('GEO', 'Geometric inequalities and optimization', 'combinatorial geometry, when geometry-first'),
 ('GEO', '3D and solid geometry', '3D geometry'),
 ('GEO', '3D and solid geometry', 'spatial geometry'),
 ('GEO', '3D and solid geometry', 'vectors in 3D'),
 ('GEO', '3D and solid geometry', 'tetrahedra'),
 ('GEO', '3D and solid geometry', 'orthocentric tetrahedra'),
 ('GEO', '3D and solid geometry', 'spheres'),
 ('GEO', '3D and solid geometry', 'circumsphere'),
 ('GEO', '3D and solid geometry', 'insphere'),
 ('GEO', '3D and solid geometry', 'sphere tangency'),
 ('GEO', '3D and solid geometry', 'dihedral angles'),
 ('GEO', '3D and solid geometry', 'planes'),
 ('GEO', '3D and solid geometry', 'projections in space'),
 ('GEO', '3D and solid geometry', 'skew lines'),
 ('GEO', '3D and solid geometry', 'distance between skew lines'),
 ('GEO', '3D and solid geometry', 'volume'),
 ('GEO', '3D and solid geometry', 'polyhedra'),
 ('GEO', '3D and solid geometry', 'regular polyhedra'),
 ('GEO', '3D and solid geometry', 'convex polyhedra'),
 ('GEO', '3D and solid geometry', 'Euler characteristic'),
 ('GEO', '3D and solid geometry', 'spherical geometry'),
 ('GEO', '3D and solid geometry', 'cone sections'),
 ('GEO', '3D and solid geometry', '3D coordinates'),
 ('GEO', '3D and solid geometry', '3D barycentrics'),
 ('GEO', '3D and solid geometry', '3D analytic geometry'),
 ('COMB', 'Counting and enumerative combinatorics', 'counting'),
 ('COMB', 'Counting and enumerative combinatorics', 'double counting'),
 ('COMB', 'Counting and enumerative combinatorics', 'bijections'),
 ('COMB', 'Counting and enumerative combinatorics', 'injections'),
 ('COMB', 'Counting and enumerative combinatorics', 'surjections'),
 ('COMB', 'Counting and enumerative combinatorics', 'inclusion-exclusion'),
 ('COMB', 'Counting and enumerative combinatorics', 'complementary counting'),
 ('COMB', 'Counting and enumerative combinatorics', 'stars and bars'),
 ('COMB', 'Counting and enumerative combinatorics', 'partitions'),
 ('COMB', 'Counting and enumerative combinatorics', 'integer partitions'),
 ('COMB', 'Counting and enumerative combinatorics', 'compositions'),
 ('COMB', 'Counting and enumerative combinatorics', 'Young diagrams'),
 ('COMB', 'Counting and enumerative combinatorics', 'Ferrers diagrams'),
 ('COMB', 'Counting and enumerative combinatorics', 'recurrence counting'),
 ('COMB', 'Counting and enumerative combinatorics', 'dynamic programming'),
 ('COMB', 'Counting and enumerative combinatorics', 'Catalan numbers'),
 ('COMB', 'Counting and enumerative combinatorics', 'Dyck paths'),
 ('COMB', 'Counting and enumerative combinatorics', 'ballot sequences'),
 ('COMB', 'Counting and enumerative combinatorics', 'Raney lemma / gas station lemma'),
 ('COMB', 'Counting and enumerative combinatorics', 'lattice paths'),
 ('COMB', 'Counting and enumerative combinatorics', 'necklaces'),
 ('COMB', 'Counting and enumerative combinatorics', 'Burnside’s lemma'),
 ('COMB', 'Counting and enumerative combinatorics', 'Polya counting'),
 ('COMB', 'Counting and enumerative combinatorics', 'Stirling numbers'),
 ('COMB', 'Counting and enumerative combinatorics', 'Bell numbers'),
 ('COMB', 'Counting and enumerative combinatorics', 'Eulerian numbers'),
 ('COMB', 'Counting and enumerative combinatorics', 'q-binomial coefficients'),
 ('COMB', 'Counting and enumerative combinatorics', 'Gaussian binomial coefficients'),
 ('COMB', 'Counting and enumerative combinatorics', 'rook polynomials'),
 ('COMB', 'Counting and enumerative combinatorics', 'matchings enumeration'),
 ('COMB', 'Counting and enumerative combinatorics', 'permutation counting'),
 ('COMB', 'Counting and enumerative combinatorics', 'derangements'),
 ('COMB', 'Counting and enumerative combinatorics', 'inversions'),
 ('COMB', 'Counting and enumerative combinatorics', 'excedances'),
 ('COMB', 'Counting and enumerative combinatorics', 'ordered partitions'),
 ('COMB', 'Counting and enumerative combinatorics', 'finite differences in counting'),
 ('COMB', 'Counting and enumerative combinatorics', 'root-of-unity filter'),
 ('COMB', 'Counting and enumerative combinatorics', 'combinatorial identities'),
 ('COMB', 'Counting and enumerative combinatorics', 'Vandermonde identity'),
 ('COMB', 'Counting and enumerative combinatorics', 'binomial coefficients'),
 ('COMB', 'Counting and enumerative combinatorics', 'binomial parity'),
 ('COMB', 'Counting and enumerative combinatorics', 'Pascal triangle'),
 ('COMB', 'Counting and enumerative combinatorics', 'Lucas theorem, when used combinatorially'),
 ('COMB', 'Counting and enumerative combinatorics', 'Catalan/Dyck/Motzkin/Narayana structures'),
 ('COMB', 'Pigeonhole, extremal principle, and averaging', 'pigeonhole principle'),
 ('COMB', 'Pigeonhole, extremal principle, and averaging', 'Dirichlet box principle'),
 ('COMB', 'Pigeonhole, extremal principle, and averaging', 'averaging'),
 ('COMB', 'Pigeonhole, extremal principle, and averaging', 'weighted averaging'),
 ('COMB', 'Pigeonhole, extremal principle, and averaging', 'extremal principle'),
 ('COMB', 'Pigeonhole, extremal principle, and averaging', 'minimal counterexample'),
 ('COMB', 'Pigeonhole, extremal principle, and averaging', 'maximal/minimal element'),
 ('COMB', 'Pigeonhole, extremal principle, and averaging', 'greedy choice'),
 ('COMB', 'Pigeonhole, extremal principle, and averaging', 'greedy algorithm'),
 ('COMB', 'Pigeonhole, extremal principle, and averaging', 'induction'),
 ('COMB', 'Pigeonhole, extremal principle, and averaging', 'strong induction'),
 ('COMB', 'Pigeonhole, extremal principle, and averaging', 'invariant/monovariant'),
 ('COMB', 'Pigeonhole, extremal principle, and averaging', 'potential function'),
 ('COMB', 'Pigeonhole, extremal principle, and averaging', 'charging argument'),
 ('COMB', 'Pigeonhole, extremal principle, and averaging', 'discharging'),
 ('COMB', 'Pigeonhole, extremal principle, and averaging', 'compactness'),
 ('COMB', 'Pigeonhole, extremal principle, and averaging', 'limiting argument'),
 ('COMB', 'Pigeonhole, extremal principle, and averaging', 'first crossing argument'),
 ('COMB', 'Pigeonhole, extremal principle, and averaging', 'first/last occurrence'),
 ('COMB', 'Pigeonhole, extremal principle, and averaging', 'worst-case analysis'),
 ('COMB', 'Pigeonhole, extremal principle, and averaging', 'adversary argument'),
 ('COMB', 'Pigeonhole, extremal principle, and averaging', 'information lower bound'),
 ('COMB', 'Pigeonhole, extremal principle, and averaging', 'decision tree lower bound'),
 ('COMB', 'Pigeonhole, extremal principle, and averaging', 'extremal construction'),
 ('COMB', 'Pigeonhole, extremal principle, and averaging', 'lower bound / upper bound matching'),
 ('COMB', 'Pigeonhole, extremal principle, and averaging', 'sharpness construction'),
 ('COMB', 'Pigeonhole, extremal principle, and averaging', 'local-to-global argument'),
 ('COMB', 'Pigeonhole, extremal principle, and averaging', 'contradiction by extremal choice'),
 ('COMB', 'Pigeonhole, extremal principle, and averaging', 'exchange argument'),
 ('COMB', 'Pigeonhole, extremal principle, and averaging', 'smoothing in combinatorics'),
 ('COMB', 'Pigeonhole, extremal principle, and averaging', 'compression / shifting'),
 ('COMB', 'Graph theory', 'graphs'),
 ('COMB', 'Graph theory', 'graph models'),
 ('COMB', 'Graph theory', 'graph coloring'),
 ('COMB', 'Graph theory', 'edge coloring'),
 ('COMB', 'Graph theory', 'vertex coloring'),
 ('COMB', 'Graph theory', 'chromatic number'),
 ('COMB', 'Graph theory', 'cliques'),
 ('COMB', 'Graph theory', 'independent sets'),
 ('COMB', 'Graph theory', 'matchings'),
 ('COMB', 'Graph theory', 'Hall’s theorem'),
 ('COMB', 'Graph theory', 'König’s theorem'),
 ('COMB', 'Graph theory', 'Tutte theorem'),
 ('COMB', 'Graph theory', 'Menger theorem'),
 ('COMB', 'Graph theory', 'max-flow/min-cut'),
 ('COMB', 'Graph theory', 'network flow'),
 ('COMB', 'Graph theory', 'bipartite graphs'),
 ('COMB', 'Graph theory', 'complete graphs'),
 ('COMB', 'Graph theory', 'complete bipartite graphs'),
 ('COMB', 'Graph theory', 'trees'),
 ('COMB', 'Graph theory', 'forests'),
 ('COMB', 'Graph theory', 'spanning trees'),
 ('COMB', 'Graph theory', 'cycles'),
 ('COMB', 'Graph theory', 'paths'),
 ('COMB', 'Graph theory', 'Hamiltonian paths/cycles'),
 ('COMB', 'Graph theory', 'Eulerian paths/cycles'),
 ('COMB', 'Graph theory', 'tournaments'),
 ('COMB', 'Graph theory', 'tournament scores'),
 ('COMB', 'Graph theory', 'degree sequences'),
 ('COMB', 'Graph theory', 'Havel-Hakimi'),
 ('COMB', 'Graph theory', 'regular graphs'),
 ('COMB', 'Graph theory', 'planar graphs'),
 ('COMB', 'Graph theory', 'Euler formula'),
 ('COMB', 'Graph theory', 'graph duality'),
 ('COMB', 'Graph theory', 'connectivity'),
 ('COMB', 'Graph theory', 'edge-connectivity'),
 ('COMB', 'Graph theory', 'vertex cuts'),
 ('COMB', 'Graph theory', 'bridges'),
 ('COMB', 'Graph theory', 'articulation points'),
 ('COMB', 'Graph theory', 'diameter'),
 ('COMB', 'Graph theory', 'domination'),
 ('COMB', 'Graph theory', 'Ramsey theory'),
 ('COMB', 'Graph theory', 'Turán theorem'),
 ('COMB', 'Graph theory', 'Mantel theorem'),
 ('COMB', 'Graph theory', 'Dirac/Ore flavor'),
 ('COMB', 'Graph theory', 'Caro-Wei bound'),
 ('COMB', 'Graph theory', 'extremal graph theory'),
 ('COMB', 'Graph theory', 'C4-free graphs'),
 ('COMB', 'Graph theory', 'triangle-free graphs'),
 ('COMB', 'Graph theory', 'graph invariants'),
 ('COMB', 'Graph theory', 'graph walks'),
 ('COMB', 'Graph theory', 'graph Laplacian'),
 ('COMB', 'Graph theory', 'spectral graph methods'),
 ('COMB', 'Graph theory', 'Cayley graphs'),
 ('COMB', 'Graph theory', 'de Bruijn graphs'),
 ('COMB', 'Graph theory', 'hypercube graphs'),
 ('COMB', 'Graph theory', 'grid graphs'),
 ('COMB', 'Graph theory', 'king graphs'),
 ('COMB', 'Graph theory', 'knight graphs'),
 ('COMB', 'Graph theory', 'graph games'),
 ('COMB', 'Graph theory', 'functional digraphs'),
 ('COMB', 'Set systems, posets, and extremal set theory', 'set systems'),
 ('COMB', 'Set systems, posets, and extremal set theory', 'subsets'),
 ('COMB', 'Set systems, posets, and extremal set theory', 'subset sums'),
 ('COMB', 'Set systems, posets, and extremal set theory', 'intersecting families'),
 ('COMB', 'Set systems, posets, and extremal set theory', 'EKR theorem flavor'),
 ('COMB', 'Set systems, posets, and extremal set theory', 'Hilton-Milner flavor'),
 ('COMB', 'Set systems, posets, and extremal set theory', 'Sperner theorem'),
 ('COMB', 'Set systems, posets, and extremal set theory', 'LYM inequality'),
 ('COMB', 'Set systems, posets, and extremal set theory', 'chains and antichains'),
 ('COMB', 'Set systems, posets, and extremal set theory', 'Dilworth theorem'),
 ('COMB', 'Set systems, posets, and extremal set theory', 'Mirsky theorem'),
 ('COMB', 'Set systems, posets, and extremal set theory', 'posets'),
 ('COMB', 'Set systems, posets, and extremal set theory', 'partial orders'),
 ('COMB', 'Set systems, posets, and extremal set theory', 'lattice of subsets'),
 ('COMB', 'Set systems, posets, and extremal set theory', 'distributive lattices'),
 ('COMB', 'Set systems, posets, and extremal set theory', 'downsets'),
 ('COMB', 'Set systems, posets, and extremal set theory', 'shadows'),
 ('COMB', 'Set systems, posets, and extremal set theory', 'sunflower lemma'),
 ('COMB', 'Set systems, posets, and extremal set theory', 'delta systems'),
 ('COMB', 'Set systems, posets, and extremal set theory', 'cover-free families'),
 ('COMB', 'Set systems, posets, and extremal set theory', 'covering designs'),
 ('COMB', 'Set systems, posets, and extremal set theory', 'packing designs'),
 ('COMB', 'Set systems, posets, and extremal set theory', 'block designs'),
 ('COMB', 'Set systems, posets, and extremal set theory', 'BIBD'),
 ('COMB', 'Set systems, posets, and extremal set theory', 'Steiner systems'),
 ('COMB', 'Set systems, posets, and extremal set theory', 'Fano plane'),
 ('COMB', 'Set systems, posets, and extremal set theory', 'finite geometry'),
 ('COMB', 'Set systems, posets, and extremal set theory', 'affine/projective finite planes'),
 ('COMB', 'Set systems, posets, and extremal set theory', 'transversals'),
 ('COMB', 'Set systems, posets, and extremal set theory', 'SDR'),
 ('COMB', 'Set systems, posets, and extremal set theory', 'Hall-type conditions'),
 ('COMB', 'Set systems, posets, and extremal set theory', 'hypergraphs'),
 ('COMB', 'Set systems, posets, and extremal set theory', 'uniform hypergraphs'),
 ('COMB', 'Set systems, posets, and extremal set theory', 'hypergraph matchings'),
 ('COMB', 'Set systems, posets, and extremal set theory', 'hypergraph coloring'),
 ('COMB', 'Set systems, posets, and extremal set theory', 'hypergraph independence'),
 ('COMB', 'Set systems, posets, and extremal set theory', 'extremal set systems'),
 ('COMB', 'Set systems, posets, and extremal set theory', 'VC dimension'),
 ('COMB', 'Set systems, posets, and extremal set theory', 'Sauer-Shelah flavor'),
 ('COMB', 'Set systems, posets, and extremal set theory', 'fractional Helly / Helly-type'),
 ('COMB', 'Set systems, posets, and extremal set theory', 'hitting sets'),
 ('COMB', 'Set systems, posets, and extremal set theory', 'blockers'),
 ('COMB', 'Set systems, posets, and extremal set theory', 'transversal number'),
 ('COMB', 'Coloring, tiling, grids, and invariants', 'coloring'),
 ('COMB', 'Coloring, tiling, grids, and invariants', '2-coloring'),
 ('COMB', 'Coloring, tiling, grids, and invariants', '3-coloring'),
 ('COMB', 'Coloring, tiling, grids, and invariants', 'modular coloring'),
 ('COMB', 'Coloring, tiling, grids, and invariants', 'checkerboard coloring'),
 ('COMB', 'Coloring, tiling, grids, and invariants', 'parity coloring'),
 ('COMB', 'Coloring, tiling, grids, and invariants', 'coloring invariants'),
 ('COMB', 'Coloring, tiling, grids, and invariants', 'tiling'),
 ('COMB', 'Coloring, tiling, grids, and invariants', 'domino tiling'),
 ('COMB', 'Coloring, tiling, grids, and invariants', 'lozenge tiling'),
 ('COMB', 'Coloring, tiling, grids, and invariants', 'polyomino tiling'),
 ('COMB', 'Coloring, tiling, grids, and invariants', 'tromino tiling'),
 ('COMB', 'Coloring, tiling, grids, and invariants', 'grid tiling'),
 ('COMB', 'Coloring, tiling, grids, and invariants', 'tiling obstructions'),
 ('COMB', 'Coloring, tiling, grids, and invariants', 'height functions'),
 ('COMB', 'Coloring, tiling, grids, and invariants', 'lattice coloring'),
 ('COMB', 'Coloring, tiling, grids, and invariants', 'board coloring'),
 ('COMB', 'Coloring, tiling, grids, and invariants', 'grid invariants'),
 ('COMB', 'Coloring, tiling, grids, and invariants', 'parity invariants'),
 ('COMB', 'Coloring, tiling, grids, and invariants', 'area invariants'),
 ('COMB', 'Coloring, tiling, grids, and invariants', 'monovariants'),
 ('COMB', 'Coloring, tiling, grids, and invariants', 'chip-firing'),
 ('COMB', 'Coloring, tiling, grids, and invariants', 'sandpile'),
 ('COMB', 'Coloring, tiling, grids, and invariants', 'Lights Out'),
 ('COMB', 'Coloring, tiling, grids, and invariants', 'cellular automata'),
 ('COMB', 'Coloring, tiling, grids, and invariants', 'toggling processes'),
 ('COMB', 'Coloring, tiling, grids, and invariants', 'row/column operations'),
 ('COMB', 'Coloring, tiling, grids, and invariants', 'sliding puzzles'),
 ('COMB', 'Coloring, tiling, grids, and invariants', 'chessboard problems'),
 ('COMB', 'Coloring, tiling, grids, and invariants', 'rook placements'),
 ('COMB', 'Coloring, tiling, grids, and invariants', 'nonattacking placements'),
 ('COMB', 'Coloring, tiling, grids, and invariants', 'lattice grids'),
 ('COMB', 'Coloring, tiling, grids, and invariants', 'triangular lattice'),
 ('COMB', 'Coloring, tiling, grids, and invariants', 'toroidal grids'),
 ('COMB', 'Coloring, tiling, grids, and invariants', 'plane arrangements'),
 ('COMB', 'Coloring, tiling, grids, and invariants', 'region counting'),
 ('COMB', 'Coloring, tiling, grids, and invariants', 'planar duality'),
 ('COMB', 'Coloring, tiling, grids, and invariants', 'Jordan curve style arguments'),
 ('COMB', 'Coloring, tiling, grids, and invariants', 'discharging on grids'),
 ('COMB', 'Coloring, tiling, grids, and invariants', 'local pattern constraints'),
 ('COMB', 'Coloring, tiling, grids, and invariants', 'forbidden patterns'),
 ('COMB', 'Games, strategies, and processes', 'games'),
 ('COMB', 'Games, strategies, and processes', 'impartial games'),
 ('COMB', 'Games, strategies, and processes', 'Sprague-Grundy theory'),
 ('COMB', 'Games, strategies, and processes', 'mex operator'),
 ('COMB', 'Games, strategies, and processes', 'P/N positions'),
 ('COMB', 'Games, strategies, and processes', 'subtraction games'),
 ('COMB', 'Games, strategies, and processes', 'strategy stealing'),
 ('COMB', 'Games, strategies, and processes', 'pairing strategy'),
 ('COMB', 'Games, strategies, and processes', 'mirroring strategy'),
 ('COMB', 'Games, strategies, and processes', 'maker-breaker games'),
 ('COMB', 'Games, strategies, and processes', 'pursuit-evasion games'),
 ('COMB', 'Games, strategies, and processes', 'adversarial games'),
 ('COMB', 'Games, strategies, and processes', 'search games'),
 ('COMB', 'Games, strategies, and processes', 'weighing puzzles'),
 ('COMB', 'Games, strategies, and processes', 'decision-tree strategies'),
 ('COMB', 'Games, strategies, and processes', 'information theory in games'),
 ('COMB', 'Games, strategies, and processes', 'invariant strategies'),
 ('COMB', 'Games, strategies, and processes', 'monovariant strategies'),
 ('COMB', 'Games, strategies, and processes', 'potential-function strategies'),
 ('COMB', 'Games, strategies, and processes', 'greedy strategies'),
 ('COMB', 'Games, strategies, and processes', 'process dynamics'),
 ('COMB', 'Games, strategies, and processes', 'termination arguments'),
 ('COMB', 'Games, strategies, and processes', 'chip-firing processes'),
 ('COMB', 'Games, strategies, and processes', 'bootstrap percolation'),
 ('COMB', 'Games, strategies, and processes', 'rotor-router flavor'),
 ('COMB', 'Games, strategies, and processes', 'random walk processes'),
 ('COMB', 'Games, strategies, and processes', 'Markov-chain flavor'),
 ('COMB', 'Games, strategies, and processes', 'scheduling games'),
 ('COMB', 'Games, strategies, and processes', 'online algorithms'),
 ('COMB', 'Games, strategies, and processes', 'worst-case strategy'),
 ('COMB', 'Games, strategies, and processes', 'adaptive strategy'),
 ('COMB', 'Games, strategies, and processes', 'hidden information'),
 ('COMB', 'Games, strategies, and processes', 'faulty device / liar games'),
 ('COMB', 'Games, strategies, and processes', 'hat guessing'),
 ('COMB', 'Games, strategies, and processes', 'coin weighing'),
 ('COMB', 'Additive/combinatorial number theory', 'additive combinatorics'),
 ('COMB', 'Additive/combinatorial number theory', 'sum-product phenomena'),
 ('COMB', 'Additive/combinatorial number theory', 'zero-sum problems'),
 ('COMB', 'Additive/combinatorial number theory', 'Kneser flavor'),
 ('COMB', 'Additive/combinatorial number theory', 'Olson-type lemmas'),
 ('COMB', 'Additive/combinatorial number theory', 'Schur theorem'),
 ('COMB', 'Additive/combinatorial number theory', 'Rado theorem'),
 ('COMB', 'Additive/combinatorial number theory', 'arithmetic progression avoidance'),
 ('COMB', 'Additive/combinatorial number theory', '3-term AP-free sets'),
 ('COMB', 'Additive/combinatorial number theory', 'product-free sets'),
 ('COMB', 'Additive/combinatorial number theory', 'restricted sumsets'),
 ('COMB', 'Additive/combinatorial number theory', 'finite cyclic groups'),
 ('COMB', 'Additive/combinatorial number theory', 'characters / Fourier on finite groups'),
 ('COMB', 'Additive/combinatorial number theory', 'roots-of-unity filter'),
 ('COMB', 'Additive/combinatorial number theory', 'additive energy'),
 ('COMB', 'Additive/combinatorial number theory', 'multiplicative energy'),
 ('COMB', 'Additive/combinatorial number theory', 'popular differences'),
 ('COMB', 'Additive/combinatorial number theory', 'density increment'),
 ('COMB', 'Additive/combinatorial number theory', 'Ramsey/additive coloring'),
 ('COMB', 'Additive/combinatorial number theory', 'zero-sum-free sequences'),
 ('COMB', 'Additive/combinatorial number theory', 'complete mappings'),
 ('COMB', 'Additive/combinatorial number theory', 'Latin squares'),
 ('COMB', 'Additive/combinatorial number theory', 'orthomorphisms'),
 ('COMB', 'Additive/combinatorial number theory', 'modular constructions'),
 ('COMB', 'Additive/combinatorial number theory', 'residue class set systems'),
 ('COMB', 'Probability, entropy, coding, and information methods', 'probabilistic method'),
 ('COMB', 'Probability, entropy, coding, and information methods', 'random coloring'),
 ('COMB', 'Probability, entropy, coding, and information methods', 'random construction'),
 ('COMB', 'Probability, entropy, coding, and information methods', 'expectation'),
 ('COMB', 'Probability, entropy, coding, and information methods', 'linearity of expectation'),
 ('COMB', 'Probability, entropy, coding, and information methods', 'variance'),
 ('COMB', 'Probability, entropy, coding, and information methods', 'second moment'),
 ('COMB', 'Probability, entropy, coding, and information methods', 'fourth moment'),
 ('COMB', 'Probability, entropy, coding, and information methods', 'Markov/Chebyshev style bounds'),
 ('COMB', 'Probability, entropy, coding, and information methods', 'Lovász Local Lemma flavor'),
 ('COMB', 'Probability, entropy, coding, and information methods', 'entropy'),
 ('COMB', 'Probability, entropy, coding, and information methods', 'Shearer-type inequalities'),
 ('COMB', 'Probability, entropy, coding, and information methods', 'coding theory'),
 ('COMB', 'Probability, entropy, coding, and information methods', 'Hamming distance'),
 ('COMB', 'Probability, entropy, coding, and information methods', 'Hamming balls'),
 ('COMB', 'Probability, entropy, coding, and information methods', 'Hamming bound'),
 ('COMB', 'Probability, entropy, coding, and information methods', 'Plotkin bound'),
 ('COMB', 'Probability, entropy, coding, and information methods', 'error-correcting codes'),
 ('COMB', 'Probability, entropy, coding, and information methods', 'covering codes'),
 ('COMB', 'Probability, entropy, coding, and information methods', 'identifying codes'),
 ('COMB', 'Probability, entropy, coding, and information methods', 'information theory'),
 ('COMB', 'Probability, entropy, coding, and information methods', 'decision trees'),
 ('COMB', 'Probability, entropy, coding, and information methods', 'adversary lower bounds'),
 ('COMB', 'Probability, entropy, coding, and information methods', 'Kraft inequality'),
 ('COMB', 'Probability, entropy, coding, and information methods', 'prefix codes'),
 ('COMB', 'Probability, entropy, coding, and information methods', 'Huffman coding analogy'),
 ('COMB', 'Probability, entropy, coding, and information methods', 'communication protocol flavor'),
 ('COMB', 'Probability, entropy, coding, and information methods', 'search lower bounds'),
 ('COMB', 'Probability, entropy, coding, and information methods', 'query complexity'),
 ('COMB', 'Probability, entropy, coding, and information methods', 'indistinguishability'),
 ('COMB', 'Probability, entropy, coding, and information methods', 'certificates'),
 ('COMB', 'Algorithms, automata, words, and constructive combinatorics', 'algorithms'),
 ('COMB', 'Algorithms, automata, words, and constructive combinatorics', 'greedy algorithms'),
 ('COMB', 'Algorithms, automata, words, and constructive combinatorics', 'constructive combinatorics'),
 ('COMB', 'Algorithms, automata, words, and constructive combinatorics', 'constructive existence'),
 ('COMB', 'Algorithms, automata, words, and constructive combinatorics', 'constructive coloring'),
 ('COMB', 'Algorithms, automata, words, and constructive combinatorics', 'constructive tiling'),
 ('COMB', 'Algorithms, automata, words, and constructive combinatorics', 'constructive graph theory'),
 ('COMB', 'Algorithms, automata, words, and constructive combinatorics', 'constructive lower/upper bounds'),
 ('COMB', 'Algorithms, automata, words, and constructive combinatorics', 'finite-state automata'),
 ('COMB', 'Algorithms, automata, words, and constructive combinatorics', 'automata on words'),
 ('COMB', 'Algorithms, automata, words, and constructive combinatorics', 'de Bruijn sequences'),
 ('COMB', 'Algorithms, automata, words, and constructive combinatorics', 'Gray codes'),
 ('COMB', 'Algorithms, automata, words, and constructive combinatorics', 'binary strings'),
 ('COMB', 'Algorithms, automata, words, and constructive combinatorics', 'ternary strings'),
 ('COMB', 'Algorithms, automata, words, and constructive combinatorics', 'word rewriting'),
 ('COMB', 'Algorithms, automata, words, and constructive combinatorics', 'string operations'),
 ('COMB', 'Algorithms, automata, words, and constructive combinatorics', 'pattern avoidance'),
 ('COMB', 'Algorithms, automata, words, and constructive combinatorics', 'forbidden words'),
 ('COMB', 'Algorithms, automata, words, and constructive combinatorics', 'subword complexity'),
 ('COMB', 'Algorithms, automata, words, and constructive combinatorics', 'Fine-Wilf theorem flavor'),
 ('COMB', 'Algorithms, automata, words, and constructive combinatorics', 'Thue-Morse sequence'),
 ('COMB', 'Algorithms, automata, words, and constructive combinatorics', 'Prouhet-Thue-Morse'),
 ('COMB', 'Algorithms, automata, words, and constructive combinatorics', 'Lyndon words'),
 ('COMB', 'Algorithms, automata, words, and constructive combinatorics', 'prefix/suffix constraints'),
 ('COMB', 'Algorithms, automata, words, and constructive combinatorics', 'sliding windows'),
 ('COMB', 'Algorithms, automata, words, and constructive combinatorics', 'run lengths'),
 ('COMB', 'Algorithms, automata, words, and constructive combinatorics', 'palindromic strings'),
 ('COMB', 'Algorithms, automata, words, and constructive combinatorics', 'stack reductions'),
 ('COMB', 'Algorithms, automata, words, and constructive combinatorics', 'state graphs'),
 ('COMB', 'Algorithms, automata, words, and constructive combinatorics', 'finite-state dynamics'),
 ('COMB', 'Algorithms, automata, words, and constructive combinatorics', 'transfer matrices'),
 ('COMB', 'Algorithms, automata, words, and constructive combinatorics', 'bitwise XOR structures'),
 ('COMB', 'Algorithms, automata, words, and constructive combinatorics', 'Boolean cube'),
 ('COMB', 'Algorithms, automata, words, and constructive combinatorics', 'hypercube walks'))
