# Generated by Django 5.1.9 on 2026-05-21 01:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pages", "0025_userproblemcompletion_confidence_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingSubtopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subtopic_uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("slug", models.SlugField(max_length=120)),
                ("title", models.CharField(max_length=120)),
                ("normalized_title", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_seeded", models.BooleanField(db_index=True, default=False)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["topic__sort_order", "sort_order", "title", "id"],
            },
        ),
        migrations.CreateModel(
            name="TrainingTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "topic_uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("code", models.CharField(max_length=16, unique=True)),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("title", models.CharField(max_length=80)),
                ("description", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["sort_order", "title", "id"],
            },
        ),
        migrations.CreateModel(
            name="TrainingMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "material_uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("slug", models.SlugField(max_length=180)),
                ("summary", models.TextField(blank=True)),
                ("body_source", models.TextField(blank=True)),
                (
                    "body_format",
                    models.CharField(
                        choices=[("markdown", "Markdown")],
                        default="markdown",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "estimated_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="training_materials_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="training_materials_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="TrainingMaterialSubtopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_subtopics",
                        to="training.trainingmaterial",
                    ),
                ),
                (
                    "subtopic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_links",
                        to="training.trainingsubtopic",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "subtopic__topic__sort_order",
                    "subtopic__sort_order",
                    "id",
                ],
            },
        ),
        migrations.AddField(
            model_name="trainingmaterial",
            name="subtopics",
            field=models.ManyToManyField(
                blank=True,
                related_name="materials",
                through="training.TrainingMaterialSubtopic",
                to="training.trainingsubtopic",
            ),
        ),
        migrations.AddField(
            model_name="trainingsubtopic",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subtopics",
                to="training.trainingtopic",
            ),
        ),
        migrations.CreateModel(
            name="TrainingMaterialProblem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                ("note", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practice_problems",
                        to="training.trainingmaterial",
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_material_links",
                        to="pages.problemsolverecord",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
                "indexes": [
                    models.Index(
                        fields=["material", "position"],
                        name="training_mat_problem_pos_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("material", "problem"),
                        name="training_material_problem_unique_problem",
                    ),
                    models.UniqueConstraint(
                        fields=("material", "position"),
                        name="training_material_problem_unique_position",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="trainingmaterialsubtopic",
            constraint=models.UniqueConstraint(
                fields=("material", "subtopic"),
                name="training_material_subtopic_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="trainingmaterial",
            index=models.Index(
                fields=["status", "-published_at"], name="training_mat_status_pub_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="trainingsubtopic",
            constraint=models.UniqueConstraint(
                fields=("topic", "slug"), name="training_subtopic_unique_topic_slug"
            ),
        ),
        migrations.AddConstraint(
            model_name="trainingsubtopic",
            constraint=models.UniqueConstraint(
                fields=("topic", "normalized_title"),
                name="training_subtopic_unique_topic_norm_title",
            ),
        ),
    ]
