from __future__ import annotations

from django.utils.text import slugify

MAX_SLUG_LENGTH = 50


def normalize_seed_title(value: str) -> str:
    return " ".join((value or "").strip().split())


def unique_slug_for_title(title: str, used_slugs: set[str]) -> str:
    base = slugify(normalize_seed_title(title))[:MAX_SLUG_LENGTH].strip("-") or "subtopic"
    candidate = base
    counter = 2
    while candidate in used_slugs:
        suffix = f"-{counter}"
        candidate = f"{base[: MAX_SLUG_LENGTH - len(suffix)].rstrip('-')}{suffix}"
        counter += 1
    return candidate


TRAINING_TAXONOMY = [
    {
        "slug": "foundations",
        "title": "Foundations",
        "description": "Proof methods, foundational structures, and core olympiad reasoning techniques.",
        "order": 5,
        "subtopics": [
            "Mathematical proof-writing",
            "Mathematical induction",
            "Extremal principle",
            "WLOG and symmetry arguments",
            "Parity arguments",
            "Constructive proofs",
            "Bounding and estimation",
            "Relations and equivalence classes",
            "Ordered structures",
        ],
    },
    {
        "slug": "algebra",
        "title": "Algebra",
        "description": "Equations, inequalities, polynomials, functions, and structural algebraic methods.",
        "order": 10,
        "subtopics": [
            "Algebraic identities",
            "Equations and systems",
            "Inequalities",
            "Polynomials",
            "Functional equations",
            "Sequences and recurrences",
            "Symmetric and cyclic expressions",
            "Vieta relations and root methods",
            "Algebraic substitutions and transformations",
            "Absolute value and piecewise algebra",
            "Exponential and logarithmic expressions",
            "Optimization and extrema",
            "Complex numbers and roots of unity",
            "Matrices and linear transformations",
            "Factorization of a^n - b^n and a^n + b^n",
            "Brahmagupta's identity",
            "Euler's four-square identity",
            "x^3 + y^3 + z^3 - 3xyz = (x+y+z)(x^2 + y^2 + z^2 - xy - yz - zx)",
            "Sophie Germain identity",
            "Simon's favourite factoring trick",
            "Binomial theorem",
            "Multinomial theorem",
            "Sum of powers formulas",
            "Lagrange's identity",
            "Telescoping series",
            "Difference equations",
            "Arithmetic progression and sum",
            "Geometric progression and sum",
            "Geometric series",
            "Fibonacci sequence",
            "Sigma and product notation",
            "Linear recurrence solving",
            "Finite differences",
            "Generating functions for recurrences",
            "Summation by parts",
            "Functional equations basics",
            "Cauchy's functional equation",
            "Jensen's functional equation",
            "Monotonicity and continuity",
            "Rewriting to recurrence relations",
            "Polynomial functional equations",
            "Expanding to complex numbers and using the fundamental theorem of algebra",
            "Polynomials are continuous",
            "Iterates of functions",
            "Domain and codomain restrictions",
            "Regularity assumptions",
            "Additive and multiplicative variants",
            "Functional equations with bijections",
            "Triangle inequality",
            "x^2 >= 0",
            "Jensen's inequality",
            "QM-AM-GM-HM",
            "Power means",
            "Muirhead's inequality",
            "Holder's inequality",
            "Cauchy-Schwarz",
            "Titu's lemma",
            "Rearrangement inequality",
            "Chebyshev's inequality",
            "Karamata's inequality",
            "Schur's inequality",
            "Lagrange multipliers",
            "Ravi substitution",
            "Weighted AM-GM",
            "Bernoulli's inequality",
            "Tangent line method",
            "Homogenization and normalization",
            "uvw or pqr method",
            "Sum of squares method",
            "Smoothing and mixing variables",
            "Nesbitt's inequality",
            "Weitzenbock's inequality",
            "Erdos-Mordell inequality",
            "Fundamental theorem of algebra",
            "Polynomial division algorithm",
            "Vieta's formulas",
            "Remainder factor theorem",
            "Rational root theorem",
            "Roots of unity",
            "Lagrange interpolation",
            "Irreducibility",
            "Gauss' lemma",
            "Eisenstein's irreducibility criterion",
            "Cohn's irreducibility criterion",
            "Perron's irreducibility criterion",
            "Algebraic numbers",
            "Minimal polynomial",
            "(x-a)^k divides P(x) implies (x-a)^(k-1) divides P'(x)",
            "Intermediate value theorem",
            "Rolle's theorem",
            "Taylor series",
            "Symmetric polynomials",
            "Rouche's theorem",
            "Chebyshev polynomials",
            "Polynomials in two or more variables",
            "Discriminants",
            "Polynomial method",
            "Combinatorial Nullstellensatz",
            "Newton's identities",
            "Integer-valued polynomials",
            "Resultants",
            "Real-rootedness and interlacing",
            "Complex number basics",
            "De Moivre's theorem",
            "Trigonometric identities",
            "Trigonometric equations",
            "Quadratic equations",
            "Systems of equations",
            "Homogeneous equations",
            "Floor, ceiling, and fractional part equations",
            "Logarithmic and exponential equations",
        ],
    },
    {
        "slug": "number-theory",
        "title": "Number Theory",
        "description": "Divisibility, congruences, primes, residues, valuations, and integer equations.",
        "order": 20,
        "subtopics": [
            "Divisibility",
            "Modular arithmetic",
            "Primes and factorization",
            "Diophantine equations",
            "Orders, residues, and primitive roots",
            "Valuations and LTE-style methods",
            "GCD, LCM, and Euclidean algorithm",
            "Chinese remainder theorem",
            "Fermat, Euler, and Wilson theorems",
            "Quadratic residues and reciprocity",
            "Arithmetic functions",
            "Pell equations and continued fractions",
            "Base representation and digit problems",
            "Infinite descent",
            "Euclid's algorithm",
            "Division algorithm",
            "GCD",
            "Bezout's identity",
            "Divisibility relations",
            "Fundamental theorem of arithmetic",
            "GCD and LCM identities",
            "Extended Euclidean algorithm",
            "Basic congruence rules",
            "Linear congruences",
            "Euler's theorem",
            "Fermat's little theorem",
            "Wilson's theorem",
            "Order of an element",
            "Primitive roots",
            "Quadratic congruences",
            "Quadratic residues",
            "Legendre symbol",
            "x^2 congruent to -1 mod p iff p congruent to 1 mod 4",
            "Euler's criterion",
            "Law of quadratic reciprocity",
            "Lucas' theorem",
            "Cyclotomic polynomials",
            "Lagrange's theorem for polynomials",
            "Modular inverse",
            "Complete residue systems",
            "Reduced residue systems",
            "Euler phi function",
            "CRT with non-coprime moduli",
            "Polynomial congruences",
            "Order modulo composite numbers",
            "Indices or discrete logarithms modulo p",
            "Carmichael function",
            "Supplement laws for Legendre symbols",
            "Jacobi symbol",
            "Kummer's theorem",
            "Linear Diophantine equations",
            "Finding contradiction modulo n",
            "p-adic valuation basics",
            "Legendre's formula",
            "Lifting the exponent lemma",
            "Pell's equation",
            "Hensel's lemma",
            "Pythagoras' theorem",
            "Fermat's Last Theorem",
            "Parametrisation of Pythagorean triples",
            "Continued fractions for Pell equations",
            "Rational parametrisation of conics",
            "Markov-type equations",
            "Bounding in Diophantine equations",
            "Irrationality proofs",
            "Continued fractions",
            "Abstract algebra basics",
            "Eisenstein's criterion",
            "Gauss' lemma",
            "Gaussian integers Z[i]",
            "Field extensions of Q",
            "Norm in Z[i]",
            "Fermat's theorem on sums of two squares",
            "Eisenstein integers",
            "Multiplicative functions",
            "Mobius function and inversion",
            "Bertrand's postulate",
            "Zsigmondy's theorem",
            "Vieta root jumping",
            "Chicken McNugget theorem",
            "Pigeonhole principle",
            "Sum of divisor function",
            "Number of divisors function",
            "Fibonacci numbers",
            "Fermat numbers",
            "Mersenne primes",
            "Euler-Euclid theorem",
            "Infinitude of primes variants",
            "Dirichlet's theorem statement",
            "Prime number theorem statement",
            "Linear recurrences modulo n",
            "Lucas sequences",
            "Divisibility sequences",
            "Number bases",
            "Floor, ceiling, and fractional part in number theory",
            "Dirichlet approximation principle",
        ],
    },
    {
        "slug": "geometry",
        "title": "Geometry",
        "description": "Synthetic, metric, transformational, and coordinate methods for olympiad geometry.",
        "order": 30,
        "subtopics": [
            "Angle chasing",
            "Cyclic quadrilaterals",
            "Similarity and homothety",
            "Power of a point",
            "Inversion",
            "Coordinate, barycentric, and complex geometry",
            "Triangle centers and classical lines",
            "Ceva, Menelaus, and mass points",
            "Tangency and radical axis",
            "Spiral similarity",
            "Area methods",
            "Trigonometric geometry",
            "Projective geometry",
            "Loci and constructions",
            "Similar triangles",
            "Circumcentre",
            "Orthocentre and its configurations",
            "Incentre",
            "Centroid",
            "Tangents",
            "Incircles and excircles",
            "Incentre/excentre lemma",
            "Radical axis",
            "Directed angles",
            "Oriented lengths and signed ratios",
            "Angle bisectors and perpendicular bisectors",
            "Area formulas",
            "Homotheties",
            "Nine-point circle",
            "Basic trigonometry",
            "Ceva's theorem",
            "Menelaus' theorem",
            "Law of Sines",
            "Law of Cosines",
            "Trig Ceva",
            "Trig Menelaus",
            "Ptolemy's theorem",
            "Ptolemy's inequality",
            "Stewart's theorem",
            "Apollonius' theorem",
            "Angle bisector theorem",
            "Euler line",
            "Euler's formula for incenter and circumcenter",
            "Feuerbach theorem",
            "Carnot's theorem",
            "Incircle/excircle configurations",
            "Simson lines",
            "Midpoints of altitudes",
            "Isogonal conjugates",
            "Isotomic conjugates",
            "Symmedians",
            "Curvilinear incircles",
            "Mixtilinear incircles",
            "Medial triangle",
            "Orthic triangle",
            "Contact or intouch triangle",
            "Excentral triangle",
            "Pedal triangle",
            "Newton line",
            "Reim's theorem",
            "Butterfly theorem",
            "Trigonometric bashing",
            "Length chasing",
            "Cartesian coordinates",
            "Complex bash",
            "Areal coordinates",
            "Barycentric coordinates",
            "Vector geometry",
            "Shoelace and area coordinates",
            "Routh's theorem",
            "Mass points",
            "HM point",
            "Isogonal conjugate of the HM point",
            "Fermat point",
            "Isodynamic point",
            "Bevan point",
            "Gergonne point",
            "Nagel point",
            "Spieker centre",
            "Lemoine point",
            "Brocard points",
            "Napoleon's theorem",
            "Cayley-Bacharach theorem",
            "Sawayama-Thebault theorem",
            "Circle tangency through homothety trick",
            "Moving points",
            "Rotations and reflections",
            "Translations and glide reflections",
            "Affine transformations",
            "General collinearity criteria",
            "General concurrence criteria",
            "Geometric constructions",
            "Locus problems",
            "Solid geometry",
            "Definition of inversion",
            "Angle conservation in inversion",
            "Overlays",
            "Orthogonal circles",
            "Inversion distance formula",
            "Images under inversion",
            "Choosing inversion radius",
            "Cross-ratio",
            "Harmonic bundles",
            "Harmonic quadrilaterals",
            "Apollonian circles",
            "Poles and polars",
            "Brocard's theorem",
            "Pascal's theorem",
            "Brianchon's theorem",
            "Purely projective problems",
            "Projective transformations",
            "Desargues' theorem",
            "Pappus' theorem",
            "La Hire's theorem",
            "Involutions on a line",
            "Conic sections",
            "Pascal/Brianchon applications with conics",
            "Miquel's theorem",
            "Miquel points",
            "Gauss-Bodenmiller theorem",
            "Miquel points of cyclic quadrilaterals",
        ],
    },
    {
        "slug": "combinatorics",
        "title": "Combinatorics",
        "description": "Counting, extremal arguments, invariants, graphs, games, and discrete structures.",
        "order": 40,
        "subtopics": [
            "Counting techniques",
            "Pigeonhole principle",
            "Invariants and monovariants",
            "Graph theory",
            "Extremal combinatorics",
            "Games and strategies",
            "Double counting",
            "Inclusion-exclusion",
            "Recursion and generating functions",
            "Coloring arguments",
            "Tiling and packing",
            "Ramsey theory",
            "Probabilistic method",
            "Posets and ordering",
            "Set basics",
            "Permutations and combinations",
            "Bijections",
            "Binomial coefficients",
            "Symmetry of Pascal's triangle",
            "Row, column, and diagonal-row sums",
            "Pascal's identity",
            "Hockey-stick identity",
            "Vandermonde's identity",
            "Recursion",
            "Stars and bars",
            "Principle of Inclusion-Exclusion",
            "Permutation groups",
            "Group actions",
            "Hall's marriage theorem",
            "Dilworth's theorem",
            "Addition and multiplication principles",
            "Complementary counting",
            "Circular arrangements",
            "Derangements",
            "Lattice paths",
            "Reflection principle",
            "Catalan numbers",
            "Stirling numbers",
            "Bell numbers",
            "Integer partitions",
            "Orbit-stabilizer principle",
            "Polya enumeration",
            "Tiling and covering problems",
            "Colouring methods",
            "Involution principle",
            "Elementary probability",
            "Expected value",
            "Convex hull",
            "Erdos-Szekeres theorem",
            "Pick's theorem",
            "Graph theory basics",
            "Handshake lemma",
            "Eulerian graphs",
            "Planar graphs",
            "Complete graph K_n",
            "Euler's formula for planar graphs",
            "Kuratowski's theorem",
            "Dirac's theorem",
            "Ore's theorem",
            "Cayley's theorem",
            "Turan's lemma",
            "Four colour theorem",
            "Zarankiewicz's lemma",
            "Tree lemmas",
            "Spanning trees",
            "Connectivity, cut vertices, bridges",
            "Graph colouring",
            "Cliques and independent sets",
            "Matching theory",
            "Planar graph inequalities",
            "Directed graphs and tournaments",
            "Small Ramsey numbers",
            "Bayes' theorem",
            "Invariants",
            "Monovariants",
            "Generating functions",
            "Game theory",
            "Strategy stealing",
            "Pairing strategy",
            "Nim",
        ],
    },
]
