# Generated by Django 5.1.9 on 2026-05-05 15:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pages", "0022_userproblemcompletion_updated_index"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProblemList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "list_uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                (
                    "visibility",
                    models.CharField(
                        choices=[("private", "Private"), ("public", "Public")],
                        db_index=True,
                        default="private",
                        max_length=16,
                    ),
                ),
                (
                    "share_token",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problem_lists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ProblemListItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problem_list_items",
                        to="pages.problemsolverecord",
                    ),
                ),
                (
                    "problem_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="problemsets.problemlist",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProblemListVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.IntegerField(
                        choices=[(-1, "Thumbs down"), (1, "Thumbs up")]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "problem_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="problemsets.problemlist",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problem_list_votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="problemlist",
            index=models.Index(
                fields=["author", "-updated_at"], name="ps_list_author_upd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="problemlist",
            index=models.Index(
                fields=["visibility", "-published_at"], name="ps_list_vis_pub_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="problemlistitem",
            index=models.Index(
                fields=["problem_list", "position"], name="ps_item_list_pos_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="problemlistitem",
            constraint=models.UniqueConstraint(
                fields=("problem_list", "problem"),
                name="problemsets_listitem_unique_list_problem",
            ),
        ),
        migrations.AddConstraint(
            model_name="problemlistitem",
            constraint=models.UniqueConstraint(
                fields=("problem_list", "position"),
                name="problemsets_listitem_unique_list_position",
            ),
        ),
        migrations.AddIndex(
            model_name="problemlistvote",
            index=models.Index(
                fields=["problem_list", "value"], name="ps_vote_list_value_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="problemlistvote",
            constraint=models.UniqueConstraint(
                fields=("problem_list", "user"),
                name="problemsets_vote_unique_list_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="problemlistvote",
            constraint=models.CheckConstraint(
                condition=models.Q(("value", -1), ("value", 1), _connector="OR"),
                name="problemsets_vote_valid_value",
            ),
        ),
    ]
