# Generated by Django 5.1.9 on 2026-05-06

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("problemsets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="problemlist",
            name="hide_mohs",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="problemlist",
            name="hide_source",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="problemlist",
            name="hide_subtopics",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="problemlist",
            name="hide_topic",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="problemlistitem",
            name="custom_title",
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
