# Generated by Django 5.1.9 on 2026-05-24

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("problemsets", "0002_problem_list_display_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="problemlistitem",
            name="comment",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="problemlistitem",
            name="hint",
            field=models.TextField(blank=True),
        ),
    ]
