# Generated by Django 5.1.9 on 2026-06-07

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("problemsets", "0003_problem_list_item_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="problemlist",
            name="hide_core_ideas",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="problemlist",
            name="hide_pitfalls",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="problemlist",
            name="hide_rationale",
            field=models.BooleanField(default=False),
        ),
    ]
