# Generated by Django 5.1.9 on 2026-03-21 04:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pages", "0015_alter_contestproblemstatement_day_label"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SolutionBlockType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("label", models.CharField(max_length=64)),
                ("description", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_system", models.BooleanField(default=True)),
                ("allows_children", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["sort_order", "label", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProblemSolution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=160)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("summary", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problem_solutions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solutions",
                        to="pages.problemsolverecord",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ProblemSolutionBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                ("title", models.CharField(blank=True, max_length=160)),
                (
                    "body_format",
                    models.CharField(
                        choices=[("latex", "LaTeX"), ("plain_text", "Plain text")],
                        default="latex",
                        max_length=16,
                    ),
                ),
                ("body_source", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent_block",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="solutions.problemsolutionblock",
                    ),
                ),
                (
                    "solution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="solutions.problemsolution",
                    ),
                ),
                (
                    "block_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solution_blocks",
                        to="solutions.solutionblocktype",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="SolutionSourceArtifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "artifact_type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("text", "Text"),
                            ("tex", "TeX"),
                            ("image", "Image"),
                            ("url", "URL"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, upload_to="solution-artifacts/%Y/%m/%d/"
                    ),
                ),
                ("original_name", models.CharField(blank=True, max_length=255)),
                ("mime_type", models.CharField(blank=True, max_length=128)),
                ("source_text", models.TextField(blank=True)),
                ("source_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "solution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_artifacts",
                        to="solutions.problemsolution",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solution_source_artifacts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="problemsolution",
            index=models.Index(
                fields=["problem", "status"], name="solutions_p_problem_6b2c1c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="problemsolution",
            index=models.Index(
                fields=["author", "status"], name="solutions_p_author__86f487_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="problemsolution",
            constraint=models.UniqueConstraint(
                fields=("problem", "author"),
                name="solutions_problemsolution_unique_problem_author",
            ),
        ),
        migrations.AddIndex(
            model_name="problemsolutionblock",
            index=models.Index(
                fields=["solution", "parent_block", "position"],
                name="solutions_p_solutio_fca4bf_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="problemsolutionblock",
            constraint=models.UniqueConstraint(
                fields=("solution", "position"),
                name="solutions_problemsolutionblock_unique_solution_position",
            ),
        ),
    ]
