# Generated by Django 5.1.9 on 2026-03-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProblemSolveRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("topic", models.CharField(max_length=32)),
                ("mohs", models.IntegerField()),
                ("contest", models.CharField(max_length=64)),
                ("problem", models.CharField(max_length=64)),
                (
                    "contest_year_problem",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("solve_date", models.DateField(blank=True, null=True)),
                ("confidence", models.TextField(blank=True, null=True)),
                ("imo_slot_guess", models.TextField(blank=True, null=True)),
                ("topic_tags", models.TextField(blank=True, null=True)),
                ("rationale", models.TextField(blank=True, null=True)),
                ("pitfalls", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-year", "contest", "problem"],
            },
        ),
    ]
