# Generated by Django 5.1.9 on 2026-03-20 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="problemsolverecord",
            name="imo_slot_guess_value",
            field=models.TextField(blank=True, null=True),
        ),
    ]
