# Generated by Django 5.1.9 on 2026-03-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_problemsolverecord_imo_slot_guess_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="problemsolverecord",
            name="rationale_value",
            field=models.TextField(blank=True, null=True),
        ),
    ]
