# Generated by Django 5.1.9 on 2026-03-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_problemsolverecord_rationale_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="problemsolverecord",
            name="pitfalls_value",
            field=models.TextField(blank=True, null=True),
        ),
    ]
