# Generated by Django 5.1.9 on 2026-03-20 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0004_problemsolverecord_pitfalls_value"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProblemTopicTechnique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("technique", models.CharField(max_length=512)),
                ("domains", models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.AddConstraint(
            model_name="problemsolverecord",
            constraint=models.UniqueConstraint(
                fields=("year", "contest", "problem"),
                name="pages_problemsolverecord_unique_year_contest_problem",
            ),
        ),
        migrations.AddField(
            model_name="problemtopictechnique",
            name="record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="topic_techniques",
                to="pages.problemsolverecord",
            ),
        ),
        migrations.AddConstraint(
            model_name="problemtopictechnique",
            constraint=models.UniqueConstraint(
                fields=("record", "technique"),
                name="pages_problemtopictechnique_unique_record_technique",
            ),
        ),
    ]
