# Generated by Django 5.1.9 on 2026-03-20 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0005_problem_topic_technique_and_unique_problem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="problemsolverecord",
            name="solve_date",
        ),
    ]
