# Generated by Django 5.1.9 on 2026-03-20 11:45

import re

from django.db import migrations


def _clean_token(value: str | None) -> str:
    return re.sub(r"\s+", " ", (value or "").strip())


def _normalize_topic_tag(value: str | None) -> str:
    return _clean_token(value).upper()


def _domains_dedup_preserve_order(domains) -> list[str]:
    if not domains:
        return []

    seen: set[str] = set()
    out: list[str] = []
    for domain in domains:
        normalized_domain = _normalize_topic_tag(domain)
        if not normalized_domain or normalized_domain in seen:
            continue
        seen.add(normalized_domain)
        out.append(normalized_domain)
    return out


def _merge_domain_lists(a, b) -> list[str]:
    out = _domains_dedup_preserve_order(a)
    seen = set(out)
    for domain in _domains_dedup_preserve_order(b):
        if domain in seen:
            continue
        seen.add(domain)
        out.append(domain)
    return out


def uppercase_problem_topic_techniques(apps, schema_editor) -> None:
    ProblemTopicTechnique = apps.get_model("pages", "ProblemTopicTechnique")

    grouped_rows: dict[tuple[int, str], list] = {}
    for row in ProblemTopicTechnique.objects.order_by("record_id", "id"):
        key = (row.record_id, _normalize_topic_tag(row.technique))
        grouped_rows.setdefault(key, []).append(row)

    for (_record_id, normalized_technique), rows in grouped_rows.items():
        keeper = rows[0]
        merged_domains: list[str] = []
        for row in rows:
            merged_domains = _merge_domain_lists(merged_domains, row.domains or [])

        duplicate_ids = [row.pk for row in rows[1:]]
        if duplicate_ids:
            ProblemTopicTechnique.objects.filter(pk__in=duplicate_ids).delete()

        updated_fields: list[str] = []
        if keeper.technique != normalized_technique:
            keeper.technique = normalized_technique
            updated_fields.append("technique")
        if list(keeper.domains or []) != merged_domains:
            keeper.domains = merged_domains
            updated_fields.append("domains")

        if updated_fields:
            keeper.save(update_fields=updated_fields)


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0006_remove_problemsolverecord_solve_date"),
    ]

    operations = [
        migrations.RunPython(
            uppercase_problem_topic_techniques,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
