# Generated by Django 5.1.9 on 2026-03-20 12:30

import uuid

from django.conf import settings
from django.db import migrations
from django.db import models


def populate_problem_uuids(apps, schema_editor) -> None:
    ProblemSolveRecord = apps.get_model("pages", "ProblemSolveRecord")

    for record in ProblemSolveRecord.objects.filter(problem_uuid__isnull=True).iterator():
        record.problem_uuid = uuid.uuid4()
        record.save(update_fields=["problem_uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0007_uppercase_problem_topic_techniques"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="problemsolverecord",
            name="problem_uuid",
            field=models.UUIDField(db_index=True, editable=False, null=True),
        ),
        migrations.RunPython(populate_problem_uuids, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="problemsolverecord",
            name="problem_uuid",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="UserProblemCompletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("completion_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="user_completions",
                        to="pages.problemsolverecord",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="problem_completions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-completion_date", "user_id", "problem_id"],
            },
        ),
        migrations.AddConstraint(
            model_name="userproblemcompletion",
            constraint=models.UniqueConstraint(
                fields=("user", "problem"),
                name="pages_userproblemcompletion_unique_user_problem",
            ),
        ),
    ]
