# Generated by Django 5.1.9 on 2026-03-20 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0008_problem_uuid_and_user_problem_completion"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContestProblemStatement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contest_year", models.IntegerField()),
                ("contest_name", models.CharField(max_length=128)),
                (
                    "contest_year_problem",
                    models.CharField(db_index=True, max_length=160),
                ),
                ("day_label", models.CharField(blank=True, max_length=32)),
                ("problem_number", models.PositiveIntegerField()),
                ("problem_code", models.CharField(max_length=16)),
                ("statement_latex", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "linked_problem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="statement_entries",
                        to="pages.problemsolverecord",
                    ),
                ),
            ],
            options={
                "ordering": ["-contest_year", "contest_name", "problem_number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("contest_year", "contest_name", "problem_number"),
                        name="pages_contestproblemstatement_unique_contest_problem",
                    )
                ],
            },
        ),
    ]
