# Generated by Django 5.1.9 on 2026-03-20 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0010_contestproblemstatement_problem_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userproblemcompletion",
            name="completion_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
