# Generated by Django 5.1.9 on 2026-03-20 21:58

from django.db import migrations


def make_completion_date_nullable(apps, schema_editor) -> None:
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(
        'ALTER TABLE "pages_userproblemcompletion" ALTER COLUMN "completion_date" DROP NOT NULL;'
    )


def make_completion_date_not_nullable(apps, schema_editor) -> None:
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(
        'ALTER TABLE "pages_userproblemcompletion" ALTER COLUMN "completion_date" SET NOT NULL;'
    )


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0011_userproblemcompletion_completion_date_nullable"),
    ]

    operations = [
        migrations.RunPython(
            make_completion_date_nullable,
            reverse_code=make_completion_date_not_nullable,
        ),
    ]
