# Generated by Django 5.1.9 on 2026-03-20 14:21

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0012_fix_userproblemcompletion_completion_date_nullability_db"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contestproblemstatement",
            options={
                "ordering": [
                    "-contest_year",
                    "contest_name",
                    "day_label",
                    "problem_number",
                    "problem_code",
                ],
            },
        ),
        migrations.RemoveConstraint(
            model_name="contestproblemstatement",
            name="pages_contestproblemstatement_unique_contest_problem",
        ),
        migrations.AddConstraint(
            model_name="contestproblemstatement",
            constraint=models.UniqueConstraint(
                fields=("contest_year", "contest_name", "problem_code"),
                name="pages_contestproblemstatement_unique_contest_problem_code",
            ),
        ),
    ]
