# Generated by Django 5.1.9 on 2026-03-20 14:42

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0013_alter_contestproblemstatement_options_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="contestproblemstatement",
            name="pages_contestproblemstatement_unique_contest_problem_code",
        ),
        migrations.AddConstraint(
            model_name="contestproblemstatement",
            constraint=models.UniqueConstraint(
                fields=("contest_year", "contest_name", "day_label", "problem_code"),
                name="pages_contestproblemstatement_unique_contest_day_problem_code",
            ),
        ),
    ]
