# Generated by Django 5.1.9 on 2026-03-21 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "pages",
            "0014_remove_contestproblemstatement_pages_contestproblemstatement_unique_contest_problem_code_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="contestproblemstatement",
            name="day_label",
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
