# Generated by Django 5.1.9 on 2026-03-21 04:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0015_alter_contestproblemstatement_day_label"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContestMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contest_uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("contest", models.CharField(max_length=64)),
                ("full_name", models.CharField(blank=True, max_length=255)),
                ("countries", models.JSONField(blank=True, default=list)),
                ("description_markdown", models.TextField(blank=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["contest"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("contest",), name="pages_contestmetadata_unique_contest"
                    )
                ],
            },
        ),
    ]
