# Generated by Django 5.1.9 on 2026-03-21 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0016_contestmetadata"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="problemsolverecord",
            name="pages_problemsolverecord_unique_year_contest_problem",
        ),
    ]
