# Generated by Django 5.1.9 on 2026-03-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "pages",
            "0017_remove_problemsolverecord_pages_problemsolverecord_unique_year_contest_problem",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="problemsolverecord",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
