# Generated by Django 5.1.9 on 2026-03-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0018_problemsolverecord_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="contestproblemstatement",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
