# Generated by Django 5.1.9 on 2026-03-23 05:37

import django.db.models.deletion
from django.db import migrations
from django.db import models


def forwards_backfill_statement_analytics(apps, schema_editor) -> None:
    ContestProblemStatement = apps.get_model("pages", "ContestProblemStatement")
    ProblemTopicTechnique = apps.get_model("pages", "ProblemTopicTechnique")
    StatementTopicTechnique = apps.get_model("pages", "StatementTopicTechnique")

    def is_blank_str(value: str | None) -> bool:
        return value is None or not str(value).strip()

    qs = ContestProblemStatement.objects.filter(linked_problem_id__isnull=False).select_related(
        "linked_problem",
    )
    for statement in qs.iterator(chunk_size=200):
        record = statement.linked_problem
        changed = False

        if is_blank_str(statement.topic):
            statement.topic = record.topic
            changed = True
        if statement.mohs is None:
            statement.mohs = record.mohs
            changed = True
        if is_blank_str(statement.source_contest):
            statement.source_contest = record.contest
            changed = True
        if is_blank_str(statement.source_problem):
            statement.source_problem = record.problem
            changed = True
        if statement.workbook_contest_year_problem is None and record.contest_year_problem:
            statement.workbook_contest_year_problem = record.contest_year_problem
            changed = True
        if is_blank_str(statement.confidence):
            statement.confidence = record.confidence or None
            changed = True
        if is_blank_str(statement.imo_slot_guess):
            statement.imo_slot_guess = record.imo_slot_guess
            changed = True
        if is_blank_str(statement.topic_tags):
            statement.topic_tags = record.topic_tags
            changed = True
        if is_blank_str(statement.rationale):
            statement.rationale = record.rationale
            changed = True
        if is_blank_str(statement.pitfalls):
            statement.pitfalls = record.pitfalls
            changed = True

        if changed:
            statement.save()

        if not StatementTopicTechnique.objects.filter(statement_id=statement.pk).exists():
            for pt in ProblemTopicTechnique.objects.filter(record_id=record.id):
                StatementTopicTechnique.objects.create(
                    statement=statement,
                    technique=pt.technique,
                    domains=list(pt.domains or []),
                )


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0020_statement_uuid_and_statement_completions"),
    ]

    operations = [
        migrations.AddField(
            model_name="contestproblemstatement",
            name="confidence",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contestproblemstatement",
            name="imo_slot_guess",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contestproblemstatement",
            name="imo_slot_guess_value",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contestproblemstatement",
            name="mohs",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contestproblemstatement",
            name="pitfalls",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contestproblemstatement",
            name="pitfalls_value",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contestproblemstatement",
            name="rationale",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contestproblemstatement",
            name="rationale_value",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contestproblemstatement",
            name="source_contest",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="contestproblemstatement",
            name="source_problem",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="contestproblemstatement",
            name="topic",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="contestproblemstatement",
            name="topic_tags",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contestproblemstatement",
            name="workbook_contest_year_problem",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.CreateModel(
            name="StatementTopicTechnique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("technique", models.CharField(max_length=512)),
                ("domains", models.JSONField(blank=True, default=list)),
                (
                    "statement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statement_topic_techniques",
                        to="pages.contestproblemstatement",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("statement", "technique"),
                        name="pages_statementtopictechnique_unique_statement_technique",
                    )
                ],
            },
        ),
        migrations.RunPython(forwards_backfill_statement_analytics, migrations.RunPython.noop),
    ]
