# Generated by Django 5.1.9 on 2026-03-23 05:37

import django.db.models.deletion
from django.db import migrations
from django.db import models


def forwards_backfill_statement_analytics(apps, schema_editor) -> None:
    from inspinia.pages.models import ContestProblemStatement
    from inspinia.pages.statement_analytics_sync import sync_statement_analytics_from_linked_problem

    qs = ContestProblemStatement.objects.filter(linked_problem_id__isnull=False).select_related(
        "linked_problem",
    )
    for statement in qs.iterator(chunk_size=200):
        sync_statement_analytics_from_linked_problem(statement)


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0020_statement_uuid_and_statement_completions"),
    ]

    operations = [
        migrations.AddField(
            model_name="contestproblemstatement",
            name="confidence",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contestproblemstatement",
            name="imo_slot_guess",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contestproblemstatement",
            name="imo_slot_guess_value",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contestproblemstatement",
            name="mohs",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contestproblemstatement",
            name="pitfalls",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contestproblemstatement",
            name="pitfalls_value",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contestproblemstatement",
            name="rationale",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contestproblemstatement",
            name="rationale_value",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contestproblemstatement",
            name="source_contest",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="contestproblemstatement",
            name="source_problem",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="contestproblemstatement",
            name="topic",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="contestproblemstatement",
            name="topic_tags",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contestproblemstatement",
            name="workbook_contest_year_problem",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.CreateModel(
            name="StatementTopicTechnique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("technique", models.CharField(max_length=512)),
                ("domains", models.JSONField(blank=True, default=list)),
                (
                    "statement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statement_topic_techniques",
                        to="pages.contestproblemstatement",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("statement", "technique"),
                        name="pages_statementtopictechnique_unique_statement_technique",
                    )
                ],
            },
        ),
        migrations.RunPython(forwards_backfill_statement_analytics, migrations.RunPython.noop),
    ]
