# Generated by Django 5.1.9 on 2026-05-04

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0021_statement_analytics_fields"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="userproblemcompletion",
            index=models.Index(fields=["-updated_at", "-id"], name="pages_upc_updated_id_idx"),
        ),
    ]
