# Generated by Django 5.1.9 on 2026-05-05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0022_userproblemcompletion_updated_index"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProblemDifficultyRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(60),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "statement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="difficulty_ratings",
                        to="pages.contestproblemstatement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problem_difficulty_ratings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "user_id", "statement_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "statement"),
                        name="pages_userproblemdifficultyrating_unique_user_statement",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("rating__gte", 0), ("rating__lte", 60)),
                        name="pages_userproblemdifficultyrating_rating_range",
                    ),
                ],
            },
        ),
    ]
