# Generated by Django 5.1.9 on 2026-05-18 02:22

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0024_page_view_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="userproblemcompletion",
            name="confidence",
            field=models.CharField(
                blank=True,
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="userproblemcompletion",
            name="first_idea_found",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userproblemcompletion",
            name="key_technique",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="userproblemcompletion",
            name="main_obstacle",
            field=models.CharField(
                blank=True,
                choices=[
                    ("idea", "Idea"),
                    ("computation", "Computation"),
                    ("proof_rigor", "Proof rigor"),
                    ("diagram", "Diagram"),
                    ("casework", "Casework"),
                ],
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="userproblemcompletion",
            name="post_mortem",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="userproblemcompletion",
            name="proof_completed",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userproblemcompletion",
            name="reattempt_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="userproblemcompletion",
            name="status",
            field=models.CharField(
                choices=[
                    ("unattempted", "Unattempted"),
                    ("attempted", "Attempted"),
                    ("solved", "Solved"),
                    ("checked", "Checked"),
                    ("written", "Written"),
                    ("published", "Published"),
                ],
                db_index=True,
                default="solved",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="userproblemcompletion",
            name="time_spent_minutes",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
