# Generated by Codex on 2026-06-07

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0025_userproblemcompletion_confidence_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contestproblemstatement",
            name="core_ideas",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contestproblemstatement",
            name="core_ideas_value",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="problemsolverecord",
            name="core_ideas",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="problemsolverecord",
            name="core_ideas_value",
            field=models.TextField(blank=True, null=True),
        ),
    ]
