# Generated by Codex on 2026-06-19

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0026_core_ideas_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="problemtopictechnique",
            name="canonical_subtopic",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="problemtopictechnique",
            name="main_topic",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="statementtopictechnique",
            name="canonical_subtopic",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="statementtopictechnique",
            name="main_topic",
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
