# Generated by Django 5.1.9 on 2026-06-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0027_topic_technique_taxonomy_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="problemtopictechnique",
            name="normalization_confidence",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="problemtopictechnique",
            name="normalization_status",
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name="problemtopictechnique",
            name="raw_tag",
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name="statementtopictechnique",
            name="normalization_confidence",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="statementtopictechnique",
            name="normalization_status",
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name="statementtopictechnique",
            name="raw_tag",
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
