# Generated by Django 5.1.9 on 2026-06-21 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0028_problemtopictechnique_normalization_confidence_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="problemtopictechnique",
            name="lemma_theorem_tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="problemtopictechnique",
            name="object_tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="problemtopictechnique",
            name="proof_roles",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="problemtopictechnique",
            name="technique_tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="statementtopictechnique",
            name="lemma_theorem_tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="statementtopictechnique",
            name="object_tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="statementtopictechnique",
            name="proof_roles",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="statementtopictechnique",
            name="technique_tags",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
