# Generated by Django 5.1.9 on 2026-06-21 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0029_problemtopictechnique_lemma_theorem_tags_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TechniqueProgressCatalogState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "singleton_key",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, unique=True
                    ),
                ),
                ("last_refreshed_at", models.DateTimeField(blank=True, null=True)),
                ("needs_rebuild", models.BooleanField(default=True)),
                ("fact_count", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Technique progress catalog state",
                "verbose_name_plural": "Technique progress catalog state",
            },
        ),
        migrations.CreateModel(
            name="TechniqueProgressFact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "layer",
                    models.CharField(
                        choices=[
                            ("main_topic", "Main topic"),
                            ("subtopic", "Subtopic"),
                            ("technique", "Technique"),
                            ("object", "Object"),
                            ("method", "Method"),
                            ("lemma", "Lemma/Theorem"),
                            ("proof_role", "Proof role"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("label", models.CharField(max_length=512)),
                ("label_key", models.CharField(max_length=512)),
                ("canonical_subtopic", models.CharField(blank=True, max_length=160)),
                (
                    "canonical_subtopic_labels",
                    models.JSONField(blank=True, default=list),
                ),
                ("main_topic", models.CharField(blank=True, max_length=32)),
                ("main_topic_labels", models.JSONField(blank=True, default=list)),
                ("search_text", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "linked_problem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="technique_progress_facts",
                        to="pages.problemsolverecord",
                    ),
                ),
                (
                    "statement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="technique_progress_facts",
                        to="pages.contestproblemstatement",
                    ),
                ),
            ],
            options={
                "ordering": ["layer", "label", "statement_id"],
                "indexes": [
                    models.Index(
                        fields=["layer", "label_key"], name="pages_tpf_layer_label_idx"
                    ),
                    models.Index(
                        fields=["linked_problem", "layer"],
                        name="pages_tpf_problem_layer_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("statement", "layer", "label_key"),
                        name="pages_techprogressfact_unique_statement_layer_label",
                    )
                ],
            },
        ),
    ]
