# Generated by Django 5.1.9 on 2026-06-22 09:44

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0031_techniqueprogressfact_gap_filter_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TechniqueBenchmarkImportBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("previewed", "Previewed"),
                            ("applied", "Applied"),
                            ("failed", "Failed"),
                            ("restored", "Restored"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "source",
                    models.CharField(default="chatgpt_copy_paste", max_length=64),
                ),
                ("prompt_text", models.TextField(blank=True)),
                ("pasted_response", models.TextField(blank=True)),
                ("rows_total", models.PositiveIntegerField(default=0)),
                ("rows_valid", models.PositiveIntegerField(default=0)),
                ("rows_invalid", models.PositiveIntegerField(default=0)),
                ("rows_created", models.PositiveIntegerField(default=0)),
                ("rows_updated", models.PositiveIntegerField(default=0)),
                ("rows_unchanged", models.PositiveIntegerField(default=0)),
                ("error_summary", models.TextField(blank=True)),
                ("preview_payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="technique_benchmark_import_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="TechniqueBenchmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("canonical_subtopic", "Canonical subtopic"),
                            ("technique", "Technique"),
                            ("object", "Object"),
                            ("method", "Method"),
                            ("lemma", "Lemma/Theorem"),
                            ("proof_role", "Proof role"),
                            ("parent_family", "Parent family"),
                        ],
                        max_length=32,
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("label_key", models.CharField(max_length=255)),
                ("normalized_label", models.CharField(blank=True, max_length=255)),
                ("parent_family", models.CharField(blank=True, max_length=255)),
                ("primary_area", models.CharField(blank=True, max_length=64)),
                ("area_labels", models.JSONField(blank=True, default=list)),
                (
                    "syllabus_core",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "contest_frequency",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "transfer_value",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "prerequisite_value",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "concept_load",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "recognition_burden",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "execution_load",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "proof_fragility",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "cross_topic_dependency",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "difficulty_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "importance_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "typical_mohs_min",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(60),
                        ],
                    ),
                ),
                (
                    "typical_mohs_max",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(60),
                        ],
                    ),
                ),
                (
                    "typical_mohs_center",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "jbmo_weight",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1.00"), max_digits=4
                    ),
                ),
                (
                    "national_weight",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1.00"), max_digits=4
                    ),
                ),
                (
                    "imo_tst_weight",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1.00"), max_digits=4
                    ),
                ),
                ("training_type", models.CharField(blank=True, max_length=64)),
                ("target_level", models.CharField(blank=True, max_length=64)),
                (
                    "benchmark_confidence",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("rationale", models.TextField(blank=True)),
                ("pitfalls", models.TextField(blank=True)),
                ("recommended_sequence", models.TextField(blank=True)),
                ("source_version", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "imported_from_batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="benchmarks",
                        to="pages.techniquebenchmarkimportbatch",
                    ),
                ),
            ],
            options={
                "ordering": ["kind", "label"],
            },
        ),
        migrations.CreateModel(
            name="TechniqueBenchmarkAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("canonical_subtopic", "Canonical subtopic"),
                            ("technique", "Technique"),
                            ("object", "Object"),
                            ("method", "Method"),
                            ("lemma", "Lemma/Theorem"),
                            ("proof_role", "Proof role"),
                            ("parent_family", "Parent family"),
                        ],
                        max_length=32,
                    ),
                ),
                ("alias_label", models.CharField(max_length=255)),
                ("alias_key", models.CharField(max_length=255)),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "benchmark",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="pages.techniquebenchmark",
                    ),
                ),
            ],
            options={
                "ordering": ["kind", "alias_label"],
                "indexes": [
                    models.Index(
                        fields=["kind", "alias_key"], name="pages_tba_kind_key_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("kind", "alias_key"),
                        name="uniq_technique_benchmark_alias_kind_key",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="techniquebenchmark",
            index=models.Index(
                fields=["kind", "label_key"], name="pages_tb_kind_label_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="techniquebenchmark",
            index=models.Index(
                fields=["parent_family"], name="pages_tb_parent_family_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="techniquebenchmark",
            index=models.Index(
                fields=["primary_area"], name="pages_tb_primary_area_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="techniquebenchmark",
            index=models.Index(
                fields=["importance_score"], name="pages_tb_importance_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="techniquebenchmark",
            index=models.Index(
                fields=["difficulty_score"], name="pages_tb_difficulty_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="techniquebenchmark",
            constraint=models.UniqueConstraint(
                fields=("kind", "label_key"),
                name="uniq_technique_benchmark_kind_label_key",
            ),
        ),
    ]
