# Generated by Django 5.1.9 on 2026-06-22 10:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0032_techniquebenchmarkimportbatch_techniquebenchmark_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="techniquebenchmark",
            name="quality_flags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name="TechniqueBenchmarkExportBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("schema_version", models.CharField(max_length=64)),
                ("target_profile", models.CharField(default="national", max_length=32)),
                ("scope_mode", models.CharField(max_length=64)),
                ("kind_filters", models.JSONField(blank=True, default=list)),
                ("topic_filters", models.JSONField(blank=True, default=dict)),
                ("min_total", models.PositiveIntegerField(default=0)),
                (
                    "coverage_max",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("remaining_min", models.PositiveIntegerField(default=0)),
                (
                    "batch_size",
                    models.PositiveSmallIntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(250),
                        ],
                    ),
                ),
                (
                    "sort_mode",
                    models.CharField(
                        default="high_remaining_low_coverage", max_length=64
                    ),
                ),
                ("frozen_row_keys", models.JSONField(blank=True, default=list)),
                ("source_payload", models.JSONField(blank=True, default=dict)),
                ("prompt_text", models.TextField(blank=True)),
                ("row_count", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("exported", "Exported"),
                            ("previewed", "Previewed"),
                            ("applied", "Applied"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="exported",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="technique_benchmark_export_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="techniquebenchmarkimportbatch",
            name="export_batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="import_batches",
                to="pages.techniquebenchmarkexportbatch",
            ),
        ),
        migrations.AddIndex(
            model_name="techniquebenchmarkexportbatch",
            index=models.Index(
                fields=["status", "created_at"], name="pages_tbeb_status_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="techniquebenchmarkexportbatch",
            index=models.Index(fields=["scope_mode"], name="pages_tbeb_scope_idx"),
        ),
    ]
