# Generated by Django 5.1.9 on 2026-06-26

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0033_techniquebenchmark_quality_flags_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="userproblemcompletion",
            index=models.Index(fields=["user", "-updated_at"], name="pages_upc_user_updated_idx"),
        ),
    ]
