# Generated by Django 5.1.9 on 2026-07-06 05:35

import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0034_userproblemcompletion_user_updated_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="techniquebenchmark",
            name="curriculum_class",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="techniquebenchmark",
            name="key_insight_spoiler_free",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="techniquebenchmark",
            name="merge_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="techniquebenchmark",
            name="mohs_scalability",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
