# Generated by Django 5.1.9 on 2026-03-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.TextField(blank=True, verbose_name="Address"),
        ),
        migrations.AddField(
            model_name="user",
            name="birthdate",
            field=models.DateField(blank=True, null=True, verbose_name="Birthdate"),
        ),
        migrations.AddField(
            model_name="user",
            name="contact_number",
            field=models.CharField(
                blank=True,
                help_text="Include the country code, for example +60 12-345 6789.",
                max_length=32,
                verbose_name="Contact number",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="discord_username",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Discord username"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("female", "Female"),
                    ("male", "Male"),
                    ("non_binary", "Non-binary"),
                    ("other", "Other"),
                    ("prefer_not_to_say", "Prefer not to say"),
                ],
                max_length=20,
                verbose_name="Gender",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="school",
            field=models.CharField(blank=True, max_length=255, verbose_name="School"),
        ),
        migrations.AddField(
            model_name="user",
            name="social_media_links",
            field=models.TextField(
                blank=True,
                help_text="Add one profile URL per line.",
                verbose_name="Social media links",
            ),
        ),
    ]
