# Generated by Django 5.1.9 on 2026-03-20 10:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_address_user_birthdate_user_contact_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("auth.login_succeeded", "Login succeeded"),
                            ("auth.login_failed", "Login failed"),
                            ("auth.logout", "Logout"),
                            ("auth.signup", "Signup"),
                            ("users.role_changed", "Role changed"),
                            ("sessions.revoked", "Session revoked"),
                            ("imports.previewed", "Workbook previewed"),
                            ("imports.completed", "Workbook imported"),
                            ("imports.failed", "Workbook import failed"),
                        ],
                        db_index=True,
                        max_length=64,
                    ),
                ),
                ("message", models.CharField(max_length=255)),
                ("session_key", models.CharField(blank=True, max_length=40)),
                ("path", models.CharField(blank=True, max_length=255)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="targeted_audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "created_at"],
                        name="users_audit_event_t_95db86_idx",
                    ),
                    models.Index(
                        fields=["actor", "created_at"],
                        name="users_audit_actor_i_e4b501_idx",
                    ),
                    models.Index(
                        fields=["target_user", "created_at"],
                        name="users_audit_target__3e749f_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(max_length=40, unique=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "last_seen_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("expires_at", models.DateTimeField()),
                (
                    "ended_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "ended_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("active", "Active"),
                            ("logged_out", "Logged out"),
                            ("revoked", "Revoked"),
                            ("expired", "Expired"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracked_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_seen_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "ended_at"],
                        name="users_users_user_id_f0eba3_idx",
                    )
                ],
            },
        ),
    ]
