# Generated by Django 5.1.9 on 2026-04-10 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "normalized_name",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("short_name", models.CharField(blank=True, max_length=64)),
                ("state", models.CharField(blank=True, db_index=True, max_length=64)),
                (
                    "school_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("day", "Day School"),
                            ("boarding", "Boarding School"),
                            ("international", "International School"),
                            ("homeschool", "Homeschool"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=32)),
                ("display_name", models.CharField(max_length=255)),
                ("season_year", models.PositiveSmallIntegerField(db_index=True)),
                (
                    "assessment_date",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("exam", "Exam"),
                            ("quiz", "Quiz"),
                            ("selection", "Selection"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "division_scope",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("junior", "Junior"),
                            ("senior", "Senior"),
                            ("girls", "Girls"),
                            ("mixed", "Mixed"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "max_score",
                    models.DecimalField(
                        decimal_places=2, default="100.00", max_digits=8
                    ),
                ),
                (
                    "default_weight",
                    models.DecimalField(
                        decimal_places=4, default="1.0000", max_digits=8
                    ),
                ),
                (
                    "result_type",
                    models.CharField(
                        choices=[
                            ("score", "Score"),
                            ("percent", "Percent"),
                            ("band", "Band"),
                            ("rank", "Rank"),
                        ],
                        default="score",
                        max_length=32,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_ranked_by_default", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["season_year", "sort_order", "code", "id"],
                "indexes": [
                    models.Index(
                        fields=["season_year", "assessment_date"],
                        name="rank_assess_year_date_idx",
                    ),
                    models.Index(
                        fields=["season_year", "division_scope"],
                        name="rank_assess_year_div_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("code", "season_year"),
                        name="rankings_assessment_unique_code_season_year",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RankingFormula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("season_year", models.PositiveSmallIntegerField(db_index=True)),
                (
                    "division",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("junior", "Junior"),
                            ("senior", "Senior"),
                            ("girls", "Girls"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("overall", "Overall Ranking"),
                            ("selection", "Selection"),
                            ("reporting", "Reporting"),
                            ("other", "Other"),
                        ],
                        default="overall",
                        max_length=32,
                    ),
                ),
                (
                    "missing_score_policy",
                    models.CharField(
                        choices=[
                            ("zero", "Treat as Zero"),
                            ("skip", "Skip Missing Score"),
                            ("require_all", "Require All Scores"),
                        ],
                        default="zero",
                        max_length=32,
                    ),
                ),
                ("tiebreak_policy", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["season_year", "division", "name", "version", "id"],
                "indexes": [
                    models.Index(
                        fields=["season_year", "division"],
                        name="rankings_formula_year_div_idx",
                    ),
                    models.Index(
                        fields=["season_year", "purpose"],
                        name="rank_formula_year_purp_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RankingFormulaItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=4, default="1.0000", max_digits=8
                    ),
                ),
                ("is_required", models.BooleanField(default=False)),
                (
                    "normalization_method",
                    models.CharField(
                        choices=[
                            ("raw", "Raw Score"),
                            ("percent", "Percent of Max Score"),
                            ("z_score", "Z-Score"),
                            ("custom", "Custom"),
                        ],
                        default="raw",
                        max_length=32,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ranking_formula_items",
                        to="rankings.assessment",
                    ),
                ),
                (
                    "ranking_formula",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="rankings.rankingformula",
                    ),
                ),
            ],
            options={
                "ordering": ["ranking_formula", "sort_order", "id"],
                "indexes": [
                    models.Index(
                        fields=["ranking_formula", "sort_order"],
                        name="rank_formula_item_sort_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("ranking_formula", "assessment"),
                        name="rankings_formulaitem_unique_formula_assessment",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("normalized_name", models.CharField(db_index=True, max_length=255)),
                (
                    "birth_year",
                    models.PositiveSmallIntegerField(
                        blank=True, db_index=True, null=True
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("female", "Female"),
                            ("male", "Male"),
                            ("non_binary", "Non-binary"),
                            ("other", "Other"),
                            ("prefer_not_to_say", "Prefer not to say"),
                        ],
                        max_length=20,
                    ),
                ),
                ("state", models.CharField(blank=True, db_index=True, max_length=64)),
                ("masked_nric", models.CharField(blank=True, max_length=32)),
                ("full_nric", models.CharField(blank=True, max_length=32)),
                ("external_code", models.CharField(blank=True, max_length=64)),
                ("legacy_code", models.CharField(blank=True, max_length=64)),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="students",
                        to="rankings.school",
                    ),
                ),
            ],
            options={
                "ordering": ["full_name", "id"],
                "indexes": [
                    models.Index(
                        fields=["normalized_name", "birth_year"],
                        name="rank_stu_name_birth_idx",
                    ),
                    models.Index(
                        fields=["school", "normalized_name"],
                        name="rank_stu_school_name_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("external_code", ""), _negated=True),
                        fields=("external_code",),
                        name="rankings_student_unique_non_empty_external_code",
                    )
                ],
            },
        ),
    ]
