# Generated by Django 5.1.9 on 2026-04-10 15:20

from django.db import migrations, models


ASSESSMENT_CATEGORY_ALIASES = {
    "exam": "test",
    "quiz": "test",
    "selection": "qualifier",
}

ASSESSMENT_RESULT_TYPE_ALIASES = {
    "percent": "score",
    "rank": "status",
}

RANKING_FORMULA_MISSING_SCORE_POLICY_ALIASES = {
    "skip": "skip_and_rescale",
    "require_all": "zero",
}

RANKING_FORMULA_ITEM_NORMALIZATION_METHOD_ALIASES = {
    "percent": "percent_of_max",
    "z_score": "zscore",
    "custom": "fixed_scale",
}


def canonicalize_token(value, aliases):
    token = " ".join((value or "").split()).lower()
    return aliases.get(token, token)


def backfill_ranking_choice_tokens(apps, schema_editor):
    Assessment = apps.get_model("rankings", "Assessment")
    RankingFormula = apps.get_model("rankings", "RankingFormula")
    RankingFormulaItem = apps.get_model("rankings", "RankingFormulaItem")

    assessments_to_update = []
    for assessment in Assessment.objects.all().only("id", "category", "result_type"):
        category = canonicalize_token(
            assessment.category,
            ASSESSMENT_CATEGORY_ALIASES,
        )
        result_type = canonicalize_token(
            assessment.result_type,
            ASSESSMENT_RESULT_TYPE_ALIASES,
        )
        if category != assessment.category or result_type != assessment.result_type:
            assessment.category = category
            assessment.result_type = result_type
            assessments_to_update.append(assessment)

    if assessments_to_update:
        Assessment.objects.bulk_update(
            assessments_to_update,
            ["category", "result_type"],
        )

    formulas_to_update = []
    used_versions_by_scope = {}
    formula_queryset = RankingFormula.objects.all().only(
        "id",
        "season_year",
        "division",
        "purpose",
        "version",
        "missing_score_policy",
    )
    for formula in formula_queryset.order_by(
        "season_year",
        "division",
        "purpose",
        "version",
        "id",
    ):
        missing_score_policy = canonicalize_token(
            formula.missing_score_policy,
            RANKING_FORMULA_MISSING_SCORE_POLICY_ALIASES,
        )
        scope = (formula.season_year, formula.division, formula.purpose)
        used_versions = used_versions_by_scope.setdefault(scope, set())
        version = formula.version
        if version in used_versions:
            version += 1
            while version in used_versions:
                version += 1
        used_versions.add(version)

        if (
            missing_score_policy != formula.missing_score_policy
            or version != formula.version
        ):
            formula.missing_score_policy = missing_score_policy
            formula.version = version
            formulas_to_update.append(formula)

    if formulas_to_update:
        RankingFormula.objects.bulk_update(
            formulas_to_update,
            ["missing_score_policy", "version"],
        )

    items_to_update = []
    for item in RankingFormulaItem.objects.all().only("id", "normalization_method"):
        normalization_method = canonicalize_token(
            item.normalization_method,
            RANKING_FORMULA_ITEM_NORMALIZATION_METHOD_ALIASES,
        )
        if normalization_method != item.normalization_method:
            item.normalization_method = normalization_method
            items_to_update.append(item)

    if items_to_update:
        RankingFormulaItem.objects.bulk_update(
            items_to_update,
            ["normalization_method"],
        )


class Migration(migrations.Migration):

    dependencies = [
        ("rankings", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(backfill_ranking_choice_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="assessment",
            name="category",
            field=models.CharField(
                choices=[
                    ("contest", "Contest"),
                    ("test", "Test"),
                    ("qualifier", "Qualifier"),
                    ("mock", "Mock"),
                    ("monthly", "Monthly"),
                    ("entrance", "Entrance"),
                    ("other", "Other"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="division_scope",
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="result_type",
            field=models.CharField(
                choices=[
                    ("score", "Score"),
                    ("band", "Band"),
                    ("medal", "Medal"),
                    ("status", "Status"),
                    ("text", "Text"),
                    ("mixed", "Mixed"),
                ],
                default="score",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="rankingformula",
            name="division",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=32
            ),
        ),
        migrations.AlterField(
            model_name="rankingformula",
            name="missing_score_policy",
            field=models.CharField(
                choices=[
                    ("zero", "Treat as Zero"),
                    ("skip_and_rescale", "Skip and Rescale"),
                ],
                default="zero",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="rankingformulaitem",
            name="normalization_method",
            field=models.CharField(
                choices=[
                    ("raw", "Raw Score"),
                    ("percent_of_max", "Percent of Max Score"),
                    ("zscore", "Z-Score"),
                    ("fixed_scale", "Fixed Scale"),
                ],
                default="raw",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="school",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="student",
            name="full_nric",
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AddConstraint(
            model_name="rankingformula",
            constraint=models.UniqueConstraint(
                fields=("season_year", "division", "purpose", "version"),
                name="rankings_formula_unique_scope_version",
            ),
        ),
    ]
