# Generated by Django 5.1.9 on 2026-04-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rankings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessment",
            name="category",
            field=models.CharField(
                choices=[
                    ("contest", "Contest"),
                    ("test", "Test"),
                    ("qualifier", "Qualifier"),
                    ("mock", "Mock"),
                    ("monthly", "Monthly"),
                    ("entrance", "Entrance"),
                    ("other", "Other"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="division_scope",
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="result_type",
            field=models.CharField(
                choices=[
                    ("score", "Score"),
                    ("band", "Band"),
                    ("medal", "Medal"),
                    ("status", "Status"),
                    ("text", "Text"),
                    ("mixed", "Mixed"),
                ],
                default="score",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="rankingformula",
            name="division",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=32
            ),
        ),
        migrations.AlterField(
            model_name="rankingformula",
            name="missing_score_policy",
            field=models.CharField(
                choices=[
                    ("zero", "Treat as Zero"),
                    ("skip_and_rescale", "Skip and Rescale"),
                ],
                default="zero",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="rankingformulaitem",
            name="normalization_method",
            field=models.CharField(
                choices=[
                    ("raw", "Raw Score"),
                    ("percent_of_max", "Percent of Max Score"),
                    ("zscore", "Z-Score"),
                    ("fixed_scale", "Fixed Scale"),
                ],
                default="raw",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="school",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="student",
            name="full_nric",
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AddConstraint(
            model_name="rankingformula",
            constraint=models.UniqueConstraint(
                fields=("season_year", "division", "purpose", "version"),
                name="rankings_formula_unique_scope_version",
            ),
        ),
    ]
