# Generated by Django 5.1.9 on 2026-04-10 15:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rankings", "0002_alter_assessment_category_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "import_type",
                    models.CharField(
                        choices=[
                            ("student_master", "Student Master"),
                            ("assessment_results", "Assessment Results"),
                            ("legacy_wide_table", "Legacy Wide Table"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "uploaded_file",
                    models.FileField(upload_to="rankings/imports/%Y/%m/%d"),
                ),
                ("original_filename", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("previewed", "Previewed"),
                            ("applied", "Applied"),
                            ("failed", "Failed"),
                            ("partial", "Partial"),
                        ],
                        db_index=True,
                        default="uploaded",
                        max_length=32,
                    ),
                ),
                ("summary_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_import_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ImportRowIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_number", models.PositiveIntegerField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("issue_code", models.CharField(max_length=64)),
                ("message", models.TextField()),
                ("raw_row_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "import_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="row_issues",
                        to="rankings.importbatch",
                    ),
                ),
            ],
            options={
                "ordering": ["import_batch", "row_number", "id"],
                "indexes": [
                    models.Index(
                        fields=["import_batch", "severity"],
                        name="rank_issue_batch_sev_idx",
                    ),
                    models.Index(
                        fields=["import_batch", "row_number"],
                        name="rank_issue_batch_row_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RankingSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season_year", models.PositiveSmallIntegerField(db_index=True)),
                (
                    "division",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=32
                    ),
                ),
                (
                    "total_score",
                    models.DecimalField(db_index=True, decimal_places=4, max_digits=12),
                ),
                (
                    "rank_overall",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "rank_within_division",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("score_breakdown_json", models.JSONField(blank=True, default=dict)),
                (
                    "last_computed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("formula_version_label", models.CharField(blank=True, max_length=64)),
                ("formula_version_hash", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ranking_formula",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="rankings.rankingformula",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ranking_snapshots",
                        to="rankings.student",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "season_year",
                    "division",
                    "rank_overall",
                    "student",
                    "id",
                ],
                "indexes": [
                    models.Index(fields=["season_year"], name="rank_snap_season_idx"),
                    models.Index(fields=["division"], name="rank_snap_div_idx"),
                    models.Index(fields=["total_score"], name="rank_snap_score_idx"),
                    models.Index(fields=["rank_overall"], name="rank_snap_rank_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("ranking_formula", "student"),
                        name="rank_snapshot_unique_pair",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StudentResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "raw_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "normalized_score",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("medal", models.CharField(blank=True, db_index=True, max_length=32)),
                ("band", models.CharField(blank=True, db_index=True, max_length=32)),
                ("status_text", models.CharField(blank=True, max_length=64)),
                ("remarks", models.TextField(blank=True)),
                ("source_url", models.URLField(blank=True)),
                ("source_file_name", models.CharField(blank=True, max_length=255)),
                ("imported_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="rankings.assessment",
                    ),
                ),
                (
                    "imported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="imported_student_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="rankings.student",
                    ),
                ),
            ],
            options={
                "ordering": ["assessment", "student", "id"],
                "indexes": [
                    models.Index(fields=["assessment"], name="rank_res_assess_idx"),
                    models.Index(fields=["student"], name="rank_res_student_idx"),
                    models.Index(fields=["raw_score"], name="rank_res_rawscore_idx"),
                    models.Index(fields=["medal"], name="rank_res_medal_idx"),
                    models.Index(fields=["band"], name="rank_res_band_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("student", "assessment"),
                        name="rank_sturesult_unique_pair",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StudentSelectionStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season_year", models.PositiveSmallIntegerField(db_index=True)),
                (
                    "division",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=32
                    ),
                ),
                ("status", models.CharField(db_index=True, max_length=32)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_selection_statuses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selection_statuses",
                        to="rankings.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-season_year", "division", "status", "student", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("student", "season_year", "division", "status"),
                        name="rank_selstatus_unique_scope",
                    )
                ],
            },
        ),
    ]
