# Generated by Django 5.1.9 on 2026-04-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rankings", "0003_importbatch_importrowissue_rankingsnapshot_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="rankingsnapshot",
            name="rank_snap_season_idx",
        ),
        migrations.RemoveIndex(
            model_name="rankingsnapshot",
            name="rank_snap_div_idx",
        ),
        migrations.RemoveIndex(
            model_name="rankingsnapshot",
            name="rank_snap_score_idx",
        ),
        migrations.RemoveIndex(
            model_name="rankingsnapshot",
            name="rank_snap_rank_idx",
        ),
        migrations.RemoveIndex(
            model_name="studentresult",
            name="rank_res_assess_idx",
        ),
        migrations.RemoveIndex(
            model_name="studentresult",
            name="rank_res_student_idx",
        ),
        migrations.RemoveIndex(
            model_name="studentresult",
            name="rank_res_medal_idx",
        ),
        migrations.RemoveIndex(
            model_name="studentresult",
            name="rank_res_band_idx",
        ),
        migrations.AlterField(
            model_name="studentselectionstatus",
            name="status",
            field=models.CharField(
                choices=[
                    ("team", "Team"),
                    ("squad", "Squad"),
                    ("watchlist", "Watchlist"),
                    ("senior", "Senior"),
                    ("junior", "Junior"),
                    ("primary", "Primary"),
                    ("pioneer", "Pioneer"),
                    ("beginner", "Beginner"),
                    ("none", "None"),
                ],
                db_index=True,
                default="none",
                max_length=32,
            ),
        ),
    ]
